namespace PokemonUI
{
    partial class PokemonUIForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(PokemonUIForm));
            this.menuPanel = new System.Windows.Forms.Panel();
            this.buttonsPanel = new System.Windows.Forms.Panel();
            this.settingsButton = new System.Windows.Forms.Button();
            this.icons = new System.Windows.Forms.ImageList(this.components);
            this.pokemonButton = new System.Windows.Forms.Button();
            this.itemsButton = new System.Windows.Forms.Button();
            this.movesButton = new System.Windows.Forms.Button();
            this.teamsButton = new System.Windows.Forms.Button();
            this.label1 = new System.Windows.Forms.Label();
            this.logoPanel = new System.Windows.Forms.Panel();
            this.appTitleLabel = new System.Windows.Forms.Label();
            this.menuTitlePanel = new System.Windows.Forms.Panel();
            this.comboBox1 = new System.Windows.Forms.ComboBox();
            this.menuTitleLabel = new System.Windows.Forms.Label();
            this.desktopPanel = new System.Windows.Forms.Panel();
            this.types = new System.Windows.Forms.ImageList(this.components);
            this.pokemonImages = new System.Windows.Forms.ImageList(this.components);
            this.itemImages = new System.Windows.Forms.ImageList(this.components);
            this.menuPanel.SuspendLayout();
            this.buttonsPanel.SuspendLayout();
            this.logoPanel.SuspendLayout();
            this.menuTitlePanel.SuspendLayout();
            this.SuspendLayout();
            // 
            // menuPanel
            // 
            this.menuPanel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(51)))), ((int)(((byte)(76)))));
            this.menuPanel.Controls.Add(this.buttonsPanel);
            this.menuPanel.Controls.Add(this.label1);
            this.menuPanel.Controls.Add(this.logoPanel);
            resources.ApplyResources(this.menuPanel, "menuPanel");
            this.menuPanel.ForeColor = System.Drawing.Color.Gainsboro;
            this.menuPanel.Name = "menuPanel";
            // 
            // buttonsPanel
            // 
            resources.ApplyResources(this.buttonsPanel, "buttonsPanel");
            this.buttonsPanel.Controls.Add(this.settingsButton);
            this.buttonsPanel.Controls.Add(this.pokemonButton);
            this.buttonsPanel.Controls.Add(this.itemsButton);
            this.buttonsPanel.Controls.Add(this.movesButton);
            this.buttonsPanel.Controls.Add(this.teamsButton);
            this.buttonsPanel.Name = "buttonsPanel";
            // 
            // settingsButton
            // 
            resources.ApplyResources(this.settingsButton, "settingsButton");
            this.settingsButton.FlatAppearance.BorderSize = 0;
            this.settingsButton.ImageList = this.icons;
            this.settingsButton.Name = "settingsButton";
            this.settingsButton.UseVisualStyleBackColor = true;
            this.settingsButton.Click += new System.EventHandler(this.settingsButton_Click);
            // 
            // icons
            // 
            this.icons.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("icons.ImageStream")));
            this.icons.TransparentColor = System.Drawing.Color.Transparent;
            this.icons.Images.SetKeyName(0, "icons8-sword-80.png");
            this.icons.Images.SetKeyName(1, "icons8-sword-64.png");
            this.icons.Images.SetKeyName(2, "icons8-gear-pok-96.png");
            this.icons.Images.SetKeyName(3, "icons8-fight-pokemon-96.png");
            this.icons.Images.SetKeyName(4, "1337524_game_go_moltres_play_pokemon_icon.png");
            this.icons.Images.SetKeyName(5, "icons8-pokedex-96.png");
            this.icons.Images.SetKeyName(6, "icons8-pokebag-96.png");
            // 
            // pokemonButton
            // 
            resources.ApplyResources(this.pokemonButton, "pokemonButton");
            this.pokemonButton.FlatAppearance.BorderSize = 0;
            this.pokemonButton.ImageList = this.icons;
            this.pokemonButton.Name = "pokemonButton";
            this.pokemonButton.UseVisualStyleBackColor = true;
            this.pokemonButton.Click += new System.EventHandler(this.pokemonButton_Click);
            // 
            // itemsButton
            // 
            resources.ApplyResources(this.itemsButton, "itemsButton");
            this.itemsButton.FlatAppearance.BorderSize = 0;
            this.itemsButton.ImageList = this.icons;
            this.itemsButton.Name = "itemsButton";
            this.itemsButton.UseVisualStyleBackColor = true;
            this.itemsButton.Click += new System.EventHandler(this.itemsButton_Click);
            // 
            // movesButton
            // 
            resources.ApplyResources(this.movesButton, "movesButton");
            this.movesButton.FlatAppearance.BorderSize = 0;
            this.movesButton.ImageList = this.icons;
            this.movesButton.Name = "movesButton";
            this.movesButton.UseVisualStyleBackColor = true;
            this.movesButton.Click += new System.EventHandler(this.movesButton_Click);
            // 
            // teamsButton
            // 
            resources.ApplyResources(this.teamsButton, "teamsButton");
            this.teamsButton.FlatAppearance.BorderSize = 0;
            this.teamsButton.ImageList = this.icons;
            this.teamsButton.Name = "teamsButton";
            this.teamsButton.UseVisualStyleBackColor = true;
            this.teamsButton.Click += new System.EventHandler(this.teamsButton_Click);
            // 
            // label1
            // 
            resources.ApplyResources(this.label1, "label1");
            this.label1.Name = "label1";
            // 
            // logoPanel
            // 
            this.logoPanel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(39)))), ((int)(((byte)(58)))));
            this.logoPanel.Controls.Add(this.appTitleLabel);
            resources.ApplyResources(this.logoPanel, "logoPanel");
            this.logoPanel.Name = "logoPanel";
            // 
            // appTitleLabel
            // 
            resources.ApplyResources(this.appTitleLabel, "appTitleLabel");
            this.appTitleLabel.Name = "appTitleLabel";
            // 
            // menuTitlePanel
            // 
            this.menuTitlePanel.BackColor = System.Drawing.SystemColors.ActiveCaption;
            this.menuTitlePanel.Controls.Add(this.comboBox1);
            this.menuTitlePanel.Controls.Add(this.menuTitleLabel);
            resources.ApplyResources(this.menuTitlePanel, "menuTitlePanel");
            this.menuTitlePanel.Name = "menuTitlePanel";
            // 
            // comboBox1
            // 
            resources.ApplyResources(this.comboBox1, "comboBox1");
            this.comboBox1.FormattingEnabled = true;
            this.comboBox1.Items.AddRange(new object[] {
            resources.GetString("comboBox1.Items"),
            resources.GetString("comboBox1.Items1"),
            resources.GetString("comboBox1.Items2")});
            this.comboBox1.Name = "comboBox1";
            this.comboBox1.SelectedIndexChanged += new System.EventHandler(this.comboBox1_SelectedIndexChanged);
            // 
            // menuTitleLabel
            // 
            resources.ApplyResources(this.menuTitleLabel, "menuTitleLabel");
            this.menuTitleLabel.ForeColor = System.Drawing.Color.Gainsboro;
            this.menuTitleLabel.Name = "menuTitleLabel";
            // 
            // desktopPanel
            // 
            resources.ApplyResources(this.desktopPanel, "desktopPanel");
            this.desktopPanel.Name = "desktopPanel";
            this.desktopPanel.Paint += new System.Windows.Forms.PaintEventHandler(this.desktopPanel_Paint);
            // 
            // types
            // 
            this.types.ColorDepth = System.Windows.Forms.ColorDepth.Depth8Bit;
            resources.ApplyResources(this.types, "types");
            this.types.TransparentColor = System.Drawing.Color.Transparent;
            // 
            // pokemonImages
            // 
            this.pokemonImages.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("pokemonImages.ImageStream")));
            this.pokemonImages.TransparentColor = System.Drawing.Color.Transparent;
            this.pokemonImages.Images.SetKeyName(0, "91.png");
            this.pokemonImages.Images.SetKeyName(1, "92.png");
            this.pokemonImages.Images.SetKeyName(2, "93.png");
            this.pokemonImages.Images.SetKeyName(3, "94.png");
            this.pokemonImages.Images.SetKeyName(4, "95.png");
            this.pokemonImages.Images.SetKeyName(5, "96.png");
            this.pokemonImages.Images.SetKeyName(6, "97.png");
            this.pokemonImages.Images.SetKeyName(7, "98.png");
            this.pokemonImages.Images.SetKeyName(8, "99.png");
            this.pokemonImages.Images.SetKeyName(9, "902.png");
            this.pokemonImages.Images.SetKeyName(10, "903.png");
            this.pokemonImages.Images.SetKeyName(11, "904.png");
            this.pokemonImages.Images.SetKeyName(12, "905.png");
            this.pokemonImages.Images.SetKeyName(13, "9.png");
            this.pokemonImages.Images.SetKeyName(14, "85.png");
            this.pokemonImages.Images.SetKeyName(15, "86.png");
            this.pokemonImages.Images.SetKeyName(16, "87.png");
            this.pokemonImages.Images.SetKeyName(17, "88.png");
            this.pokemonImages.Images.SetKeyName(18, "89.png");
            this.pokemonImages.Images.SetKeyName(19, "90.png");
            this.pokemonImages.Images.SetKeyName(20, "841.png");
            this.pokemonImages.Images.SetKeyName(21, "842.png");
            this.pokemonImages.Images.SetKeyName(22, "843.png");
            this.pokemonImages.Images.SetKeyName(23, "844.png");
            this.pokemonImages.Images.SetKeyName(24, "845.png");
            this.pokemonImages.Images.SetKeyName(25, "846.png");
            this.pokemonImages.Images.SetKeyName(26, "847.png");
            this.pokemonImages.Images.SetKeyName(27, "848.png");
            this.pokemonImages.Images.SetKeyName(28, "849.png");
            this.pokemonImages.Images.SetKeyName(29, "850.png");
            this.pokemonImages.Images.SetKeyName(30, "851.png");
            this.pokemonImages.Images.SetKeyName(31, "852.png");
            this.pokemonImages.Images.SetKeyName(32, "853.png");
            this.pokemonImages.Images.SetKeyName(33, "854.png");
            this.pokemonImages.Images.SetKeyName(34, "855.png");
            this.pokemonImages.Images.SetKeyName(35, "856.png");
            this.pokemonImages.Images.SetKeyName(36, "857.png");
            this.pokemonImages.Images.SetKeyName(37, "858.png");
            this.pokemonImages.Images.SetKeyName(38, "859.png");
            this.pokemonImages.Images.SetKeyName(39, "860.png");
            this.pokemonImages.Images.SetKeyName(40, "861.png");
            this.pokemonImages.Images.SetKeyName(41, "862.png");
            this.pokemonImages.Images.SetKeyName(42, "863.png");
            this.pokemonImages.Images.SetKeyName(43, "864.png");
            this.pokemonImages.Images.SetKeyName(44, "865.png");
            this.pokemonImages.Images.SetKeyName(45, "866.png");
            this.pokemonImages.Images.SetKeyName(46, "867.png");
            this.pokemonImages.Images.SetKeyName(47, "868.png");
            this.pokemonImages.Images.SetKeyName(48, "869.png");
            this.pokemonImages.Images.SetKeyName(49, "870.png");
            this.pokemonImages.Images.SetKeyName(50, "871.png");
            this.pokemonImages.Images.SetKeyName(51, "872.png");
            this.pokemonImages.Images.SetKeyName(52, "873.png");
            this.pokemonImages.Images.SetKeyName(53, "874.png");
            this.pokemonImages.Images.SetKeyName(54, "875.png");
            this.pokemonImages.Images.SetKeyName(55, "876.png");
            this.pokemonImages.Images.SetKeyName(56, "877.png");
            this.pokemonImages.Images.SetKeyName(57, "878.png");
            this.pokemonImages.Images.SetKeyName(58, "879.png");
            this.pokemonImages.Images.SetKeyName(59, "880.png");
            this.pokemonImages.Images.SetKeyName(60, "881.png");
            this.pokemonImages.Images.SetKeyName(61, "882.png");
            this.pokemonImages.Images.SetKeyName(62, "883.png");
            this.pokemonImages.Images.SetKeyName(63, "884.png");
            this.pokemonImages.Images.SetKeyName(64, "885.png");
            this.pokemonImages.Images.SetKeyName(65, "886.png");
            this.pokemonImages.Images.SetKeyName(66, "887.png");
            this.pokemonImages.Images.SetKeyName(67, "888.png");
            this.pokemonImages.Images.SetKeyName(68, "889.png");
            this.pokemonImages.Images.SetKeyName(69, "890.png");
            this.pokemonImages.Images.SetKeyName(70, "891.png");
            this.pokemonImages.Images.SetKeyName(71, "892.png");
            this.pokemonImages.Images.SetKeyName(72, "893.png");
            this.pokemonImages.Images.SetKeyName(73, "894.png");
            this.pokemonImages.Images.SetKeyName(74, "895.png");
            this.pokemonImages.Images.SetKeyName(75, "896.png");
            this.pokemonImages.Images.SetKeyName(76, "897.png");
            this.pokemonImages.Images.SetKeyName(77, "898.png");
            this.pokemonImages.Images.SetKeyName(78, "899.png");
            this.pokemonImages.Images.SetKeyName(79, "900.png");
            this.pokemonImages.Images.SetKeyName(80, "901.png");
            this.pokemonImages.Images.SetKeyName(81, "8.png");
            this.pokemonImages.Images.SetKeyName(82, "79.png");
            this.pokemonImages.Images.SetKeyName(83, "80.png");
            this.pokemonImages.Images.SetKeyName(84, "81.png");
            this.pokemonImages.Images.SetKeyName(85, "82.png");
            this.pokemonImages.Images.SetKeyName(86, "83.png");
            this.pokemonImages.Images.SetKeyName(87, "84.png");
            this.pokemonImages.Images.SetKeyName(88, "782.png");
            this.pokemonImages.Images.SetKeyName(89, "783.png");
            this.pokemonImages.Images.SetKeyName(90, "784.png");
            this.pokemonImages.Images.SetKeyName(91, "785.png");
            this.pokemonImages.Images.SetKeyName(92, "786.png");
            this.pokemonImages.Images.SetKeyName(93, "787.png");
            this.pokemonImages.Images.SetKeyName(94, "788.png");
            this.pokemonImages.Images.SetKeyName(95, "789.png");
            this.pokemonImages.Images.SetKeyName(96, "790.png");
            this.pokemonImages.Images.SetKeyName(97, "791.png");
            this.pokemonImages.Images.SetKeyName(98, "792.png");
            this.pokemonImages.Images.SetKeyName(99, "793.png");
            this.pokemonImages.Images.SetKeyName(100, "794.png");
            this.pokemonImages.Images.SetKeyName(101, "795.png");
            this.pokemonImages.Images.SetKeyName(102, "796.png");
            this.pokemonImages.Images.SetKeyName(103, "797.png");
            this.pokemonImages.Images.SetKeyName(104, "798.png");
            this.pokemonImages.Images.SetKeyName(105, "799.png");
            this.pokemonImages.Images.SetKeyName(106, "800.png");
            this.pokemonImages.Images.SetKeyName(107, "801.png");
            this.pokemonImages.Images.SetKeyName(108, "802.png");
            this.pokemonImages.Images.SetKeyName(109, "803.png");
            this.pokemonImages.Images.SetKeyName(110, "804.png");
            this.pokemonImages.Images.SetKeyName(111, "804s.png");
            this.pokemonImages.Images.SetKeyName(112, "805.png");
            this.pokemonImages.Images.SetKeyName(113, "806.png");
            this.pokemonImages.Images.SetKeyName(114, "807.png");
            this.pokemonImages.Images.SetKeyName(115, "808.png");
            this.pokemonImages.Images.SetKeyName(116, "809.png");
            this.pokemonImages.Images.SetKeyName(117, "810.png");
            this.pokemonImages.Images.SetKeyName(118, "811.png");
            this.pokemonImages.Images.SetKeyName(119, "812.png");
            this.pokemonImages.Images.SetKeyName(120, "813.png");
            this.pokemonImages.Images.SetKeyName(121, "814.png");
            this.pokemonImages.Images.SetKeyName(122, "815.png");
            this.pokemonImages.Images.SetKeyName(123, "816.png");
            this.pokemonImages.Images.SetKeyName(124, "817.png");
            this.pokemonImages.Images.SetKeyName(125, "818.png");
            this.pokemonImages.Images.SetKeyName(126, "819.png");
            this.pokemonImages.Images.SetKeyName(127, "820.png");
            this.pokemonImages.Images.SetKeyName(128, "821.png");
            this.pokemonImages.Images.SetKeyName(129, "822.png");
            this.pokemonImages.Images.SetKeyName(130, "823.png");
            this.pokemonImages.Images.SetKeyName(131, "824.png");
            this.pokemonImages.Images.SetKeyName(132, "825.png");
            this.pokemonImages.Images.SetKeyName(133, "826.png");
            this.pokemonImages.Images.SetKeyName(134, "827.png");
            this.pokemonImages.Images.SetKeyName(135, "828.png");
            this.pokemonImages.Images.SetKeyName(136, "829.png");
            this.pokemonImages.Images.SetKeyName(137, "830.png");
            this.pokemonImages.Images.SetKeyName(138, "831.png");
            this.pokemonImages.Images.SetKeyName(139, "832.png");
            this.pokemonImages.Images.SetKeyName(140, "833.png");
            this.pokemonImages.Images.SetKeyName(141, "834.png");
            this.pokemonImages.Images.SetKeyName(142, "835.png");
            this.pokemonImages.Images.SetKeyName(143, "836.png");
            this.pokemonImages.Images.SetKeyName(144, "837.png");
            this.pokemonImages.Images.SetKeyName(145, "838.png");
            this.pokemonImages.Images.SetKeyName(146, "839.png");
            this.pokemonImages.Images.SetKeyName(147, "840.png");
            this.pokemonImages.Images.SetKeyName(148, "75.png");
            this.pokemonImages.Images.SetKeyName(149, "76.png");
            this.pokemonImages.Images.SetKeyName(150, "77.png");
            this.pokemonImages.Images.SetKeyName(151, "78.png");
            this.pokemonImages.Images.SetKeyName(152, "743.png");
            this.pokemonImages.Images.SetKeyName(153, "744.png");
            this.pokemonImages.Images.SetKeyName(154, "745.png");
            this.pokemonImages.Images.SetKeyName(155, "746.png");
            this.pokemonImages.Images.SetKeyName(156, "747.png");
            this.pokemonImages.Images.SetKeyName(157, "748.png");
            this.pokemonImages.Images.SetKeyName(158, "749.png");
            this.pokemonImages.Images.SetKeyName(159, "750.png");
            this.pokemonImages.Images.SetKeyName(160, "751.png");
            this.pokemonImages.Images.SetKeyName(161, "752.png");
            this.pokemonImages.Images.SetKeyName(162, "753.png");
            this.pokemonImages.Images.SetKeyName(163, "754.png");
            this.pokemonImages.Images.SetKeyName(164, "755.png");
            this.pokemonImages.Images.SetKeyName(165, "756.png");
            this.pokemonImages.Images.SetKeyName(166, "757.png");
            this.pokemonImages.Images.SetKeyName(167, "758.png");
            this.pokemonImages.Images.SetKeyName(168, "759.png");
            this.pokemonImages.Images.SetKeyName(169, "760.png");
            this.pokemonImages.Images.SetKeyName(170, "761.png");
            this.pokemonImages.Images.SetKeyName(171, "762.png");
            this.pokemonImages.Images.SetKeyName(172, "763.png");
            this.pokemonImages.Images.SetKeyName(173, "764.png");
            this.pokemonImages.Images.SetKeyName(174, "765.png");
            this.pokemonImages.Images.SetKeyName(175, "766.png");
            this.pokemonImages.Images.SetKeyName(176, "767.png");
            this.pokemonImages.Images.SetKeyName(177, "768.png");
            this.pokemonImages.Images.SetKeyName(178, "769.png");
            this.pokemonImages.Images.SetKeyName(179, "770.png");
            this.pokemonImages.Images.SetKeyName(180, "771.png");
            this.pokemonImages.Images.SetKeyName(181, "772.png");
            this.pokemonImages.Images.SetKeyName(182, "773.png");
            this.pokemonImages.Images.SetKeyName(183, "774.png");
            this.pokemonImages.Images.SetKeyName(184, "775.png");
            this.pokemonImages.Images.SetKeyName(185, "776.png");
            this.pokemonImages.Images.SetKeyName(186, "777.png");
            this.pokemonImages.Images.SetKeyName(187, "778.png");
            this.pokemonImages.Images.SetKeyName(188, "779.png");
            this.pokemonImages.Images.SetKeyName(189, "780.png");
            this.pokemonImages.Images.SetKeyName(190, "781.png");
            this.pokemonImages.Images.SetKeyName(191, "7.png");
            this.pokemonImages.Images.SetKeyName(192, "70.png");
            this.pokemonImages.Images.SetKeyName(193, "71.png");
            this.pokemonImages.Images.SetKeyName(194, "72.png");
            this.pokemonImages.Images.SetKeyName(195, "73.png");
            this.pokemonImages.Images.SetKeyName(196, "74.png");
            this.pokemonImages.Images.SetKeyName(197, "695.png");
            this.pokemonImages.Images.SetKeyName(198, "696.png");
            this.pokemonImages.Images.SetKeyName(199, "697.png");
            this.pokemonImages.Images.SetKeyName(200, "698.png");
            this.pokemonImages.Images.SetKeyName(201, "699.png");
            this.pokemonImages.Images.SetKeyName(202, "700.png");
            this.pokemonImages.Images.SetKeyName(203, "701.png");
            this.pokemonImages.Images.SetKeyName(204, "702.png");
            this.pokemonImages.Images.SetKeyName(205, "703.png");
            this.pokemonImages.Images.SetKeyName(206, "704.png");
            this.pokemonImages.Images.SetKeyName(207, "705.png");
            this.pokemonImages.Images.SetKeyName(208, "706.png");
            this.pokemonImages.Images.SetKeyName(209, "707.png");
            this.pokemonImages.Images.SetKeyName(210, "708.png");
            this.pokemonImages.Images.SetKeyName(211, "709.png");
            this.pokemonImages.Images.SetKeyName(212, "710.png");
            this.pokemonImages.Images.SetKeyName(213, "711.png");
            this.pokemonImages.Images.SetKeyName(214, "712.png");
            this.pokemonImages.Images.SetKeyName(215, "713.png");
            this.pokemonImages.Images.SetKeyName(216, "714.png");
            this.pokemonImages.Images.SetKeyName(217, "715.png");
            this.pokemonImages.Images.SetKeyName(218, "716.png");
            this.pokemonImages.Images.SetKeyName(219, "717.png");
            this.pokemonImages.Images.SetKeyName(220, "718.png");
            this.pokemonImages.Images.SetKeyName(221, "719.png");
            this.pokemonImages.Images.SetKeyName(222, "720.png");
            this.pokemonImages.Images.SetKeyName(223, "721.png");
            this.pokemonImages.Images.SetKeyName(224, "722.png");
            this.pokemonImages.Images.SetKeyName(225, "723.png");
            this.pokemonImages.Images.SetKeyName(226, "724.png");
            this.pokemonImages.Images.SetKeyName(227, "725.png");
            this.pokemonImages.Images.SetKeyName(228, "726.png");
            this.pokemonImages.Images.SetKeyName(229, "727.png");
            this.pokemonImages.Images.SetKeyName(230, "728.png");
            this.pokemonImages.Images.SetKeyName(231, "729.png");
            this.pokemonImages.Images.SetKeyName(232, "730.png");
            this.pokemonImages.Images.SetKeyName(233, "731.png");
            this.pokemonImages.Images.SetKeyName(234, "732.png");
            this.pokemonImages.Images.SetKeyName(235, "733.png");
            this.pokemonImages.Images.SetKeyName(236, "734.png");
            this.pokemonImages.Images.SetKeyName(237, "735.png");
            this.pokemonImages.Images.SetKeyName(238, "736.png");
            this.pokemonImages.Images.SetKeyName(239, "737.png");
            this.pokemonImages.Images.SetKeyName(240, "738.png");
            this.pokemonImages.Images.SetKeyName(241, "739.png");
            this.pokemonImages.Images.SetKeyName(242, "740.png");
            this.pokemonImages.Images.SetKeyName(243, "741.png");
            this.pokemonImages.Images.SetKeyName(244, "742.png");
            this.pokemonImages.Images.SetKeyName(245, "67.png");
            this.pokemonImages.Images.SetKeyName(246, "68.png");
            this.pokemonImages.Images.SetKeyName(247, "69.png");
            this.pokemonImages.Images.SetKeyName(248, "666.png");
            this.pokemonImages.Images.SetKeyName(249, "667.png");
            this.pokemonImages.Images.SetKeyName(250, "668.png");
            this.pokemonImages.Images.SetKeyName(251, "669.png");
            this.pokemonImages.Images.SetKeyName(252, "670.png");
            this.pokemonImages.Images.SetKeyName(253, "671.png");
            this.pokemonImages.Images.SetKeyName(254, "672.png");
            this.pokemonImages.Images.SetKeyName(255, "673.png");
            this.pokemonImages.Images.SetKeyName(256, "674.png");
            this.pokemonImages.Images.SetKeyName(257, "675.png");
            this.pokemonImages.Images.SetKeyName(258, "676.png");
            this.pokemonImages.Images.SetKeyName(259, "677.png");
            this.pokemonImages.Images.SetKeyName(260, "678.png");
            this.pokemonImages.Images.SetKeyName(261, "679.png");
            this.pokemonImages.Images.SetKeyName(262, "680.png");
            this.pokemonImages.Images.SetKeyName(263, "681.png");
            this.pokemonImages.Images.SetKeyName(264, "682.png");
            this.pokemonImages.Images.SetKeyName(265, "683.png");
            this.pokemonImages.Images.SetKeyName(266, "684.png");
            this.pokemonImages.Images.SetKeyName(267, "685.png");
            this.pokemonImages.Images.SetKeyName(268, "686.png");
            this.pokemonImages.Images.SetKeyName(269, "687.png");
            this.pokemonImages.Images.SetKeyName(270, "688.png");
            this.pokemonImages.Images.SetKeyName(271, "689.png");
            this.pokemonImages.Images.SetKeyName(272, "690.png");
            this.pokemonImages.Images.SetKeyName(273, "691.png");
            this.pokemonImages.Images.SetKeyName(274, "692.png");
            this.pokemonImages.Images.SetKeyName(275, "693.png");
            this.pokemonImages.Images.SetKeyName(276, "694.png");
            this.pokemonImages.Images.SetKeyName(277, "64.png");
            this.pokemonImages.Images.SetKeyName(278, "65.png");
            this.pokemonImages.Images.SetKeyName(279, "66.png");
            this.pokemonImages.Images.SetKeyName(280, "635.png");
            this.pokemonImages.Images.SetKeyName(281, "636.png");
            this.pokemonImages.Images.SetKeyName(282, "637.png");
            this.pokemonImages.Images.SetKeyName(283, "638.png");
            this.pokemonImages.Images.SetKeyName(284, "639.png");
            this.pokemonImages.Images.SetKeyName(285, "640.png");
            this.pokemonImages.Images.SetKeyName(286, "641.png");
            this.pokemonImages.Images.SetKeyName(287, "642.png");
            this.pokemonImages.Images.SetKeyName(288, "643.png");
            this.pokemonImages.Images.SetKeyName(289, "644.png");
            this.pokemonImages.Images.SetKeyName(290, "645.png");
            this.pokemonImages.Images.SetKeyName(291, "646.png");
            this.pokemonImages.Images.SetKeyName(292, "647.png");
            this.pokemonImages.Images.SetKeyName(293, "648.png");
            this.pokemonImages.Images.SetKeyName(294, "649.png");
            this.pokemonImages.Images.SetKeyName(295, "650.png");
            this.pokemonImages.Images.SetKeyName(296, "651.png");
            this.pokemonImages.Images.SetKeyName(297, "652.png");
            this.pokemonImages.Images.SetKeyName(298, "653.png");
            this.pokemonImages.Images.SetKeyName(299, "654.png");
            this.pokemonImages.Images.SetKeyName(300, "655.png");
            this.pokemonImages.Images.SetKeyName(301, "656.png");
            this.pokemonImages.Images.SetKeyName(302, "657.png");
            this.pokemonImages.Images.SetKeyName(303, "658.png");
            this.pokemonImages.Images.SetKeyName(304, "659.png");
            this.pokemonImages.Images.SetKeyName(305, "660.png");
            this.pokemonImages.Images.SetKeyName(306, "661.png");
            this.pokemonImages.Images.SetKeyName(307, "662.png");
            this.pokemonImages.Images.SetKeyName(308, "663.png");
            this.pokemonImages.Images.SetKeyName(309, "664.png");
            // 
            // itemImages
            // 
            this.itemImages.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("itemImages.ImageStream")));
            this.itemImages.TransparentColor = System.Drawing.Color.Transparent;
            this.itemImages.Images.SetKeyName(0, "yellow-nectar.png");
            this.itemImages.Images.SetKeyName(1, "yellow-petal.png");
            this.itemImages.Images.SetKeyName(2, "yellow-scarf.png");
            this.itemImages.Images.SetKeyName(3, "yellow-shard.png");
            this.itemImages.Images.SetKeyName(4, "zap-plate.png");
            this.itemImages.Images.SetKeyName(5, "zinc.png");
            this.itemImages.Images.SetKeyName(6, "zoom-lens.png");
            this.itemImages.Images.SetKeyName(7, "z-power-ring.png");
            this.itemImages.Images.SetKeyName(8, "z-ring.png");
            this.itemImages.Images.SetKeyName(9, "zygarde-cube.png");
            this.itemImages.Images.SetKeyName(10, "travel-trunk.png");
            this.itemImages.Images.SetKeyName(11, "tri-pass.png");
            this.itemImages.Images.SetKeyName(12, "tropic-mail.png");
            this.itemImages.Images.SetKeyName(13, "tunnel-mail.png");
            this.itemImages.Images.SetKeyName(14, "twisted-spoon.png");
            this.itemImages.Images.SetKeyName(15, "tyranitarite.png");
            this.itemImages.Images.SetKeyName(16, "ultra-ball.png");
            this.itemImages.Images.SetKeyName(17, "ultranecrozium-z--bag.png");
            this.itemImages.Images.SetKeyName(18, "ultranecrozium-z--held.png");
            this.itemImages.Images.SetKeyName(19, "unknown.png");
            this.itemImages.Images.SetKeyName(20, "unown-report.png");
            this.itemImages.Images.SetKeyName(21, "up-grade.png");
            this.itemImages.Images.SetKeyName(22, "venusaurite.png");
            this.itemImages.Images.SetKeyName(23, "vs-recorder.png");
            this.itemImages.Images.SetKeyName(24, "vs-seeker.png");
            this.itemImages.Images.SetKeyName(25, "wacan-berry.png");
            this.itemImages.Images.SetKeyName(26, "wailmer-pail.png");
            this.itemImages.Images.SetKeyName(27, "water-gem.png");
            this.itemImages.Images.SetKeyName(28, "waterium-z--bag.png");
            this.itemImages.Images.SetKeyName(29, "waterium-z--held.png");
            this.itemImages.Images.SetKeyName(30, "water-memory.png");
            this.itemImages.Images.SetKeyName(31, "water-stone.png");
            this.itemImages.Images.SetKeyName(32, "watmel-berry.png");
            this.itemImages.Images.SetKeyName(33, "wave-incense.png");
            this.itemImages.Images.SetKeyName(34, "wave-mail.png");
            this.itemImages.Images.SetKeyName(35, "weakness-policy.png");
            this.itemImages.Images.SetKeyName(36, "wepear-berry.png");
            this.itemImages.Images.SetKeyName(37, "whipped-dream.png");
            this.itemImages.Images.SetKeyName(38, "white-apricorn.png");
            this.itemImages.Images.SetKeyName(39, "white-flute.png");
            this.itemImages.Images.SetKeyName(40, "white-herb.png");
            this.itemImages.Images.SetKeyName(41, "wide-lens.png");
            this.itemImages.Images.SetKeyName(42, "wiki-berry.png");
            this.itemImages.Images.SetKeyName(43, "wise-glasses.png");
            this.itemImages.Images.SetKeyName(44, "wood-mail.png");
            this.itemImages.Images.SetKeyName(45, "works-key.png");
            this.itemImages.Images.SetKeyName(46, "x-accuracy.png");
            this.itemImages.Images.SetKeyName(47, "x-accuracy-2.png");
            this.itemImages.Images.SetKeyName(48, "x-accuracy-3.png");
            this.itemImages.Images.SetKeyName(49, "x-accuracy-6.png");
            this.itemImages.Images.SetKeyName(50, "x-attack.png");
            this.itemImages.Images.SetKeyName(51, "x-attack-2.png");
            this.itemImages.Images.SetKeyName(52, "x-attack-3.png");
            this.itemImages.Images.SetKeyName(53, "x-attack-6.png");
            this.itemImages.Images.SetKeyName(54, "x-defense.png");
            this.itemImages.Images.SetKeyName(55, "x-defense-2.png");
            this.itemImages.Images.SetKeyName(56, "x-defense-3.png");
            this.itemImages.Images.SetKeyName(57, "x-defense-6.png");
            this.itemImages.Images.SetKeyName(58, "x-sp-atk.png");
            this.itemImages.Images.SetKeyName(59, "x-sp-atk-2.png");
            this.itemImages.Images.SetKeyName(60, "x-sp-atk-3.png");
            this.itemImages.Images.SetKeyName(61, "x-sp-atk-6.png");
            this.itemImages.Images.SetKeyName(62, "x-sp-def.png");
            this.itemImages.Images.SetKeyName(63, "x-sp-def-2.png");
            this.itemImages.Images.SetKeyName(64, "x-sp-def-3.png");
            this.itemImages.Images.SetKeyName(65, "x-sp-def-6.png");
            this.itemImages.Images.SetKeyName(66, "x-speed.png");
            this.itemImages.Images.SetKeyName(67, "x-speed-2.png");
            this.itemImages.Images.SetKeyName(68, "x-speed-3.png");
            this.itemImages.Images.SetKeyName(69, "x-speed-6.png");
            this.itemImages.Images.SetKeyName(70, "xtranceiver--red.png");
            this.itemImages.Images.SetKeyName(71, "xtranceiver--yellow.png");
            this.itemImages.Images.SetKeyName(72, "xtransceiver.png");
            this.itemImages.Images.SetKeyName(73, "xtransceiver-red.png");
            this.itemImages.Images.SetKeyName(74, "xtransceiver-yellow.png");
            this.itemImages.Images.SetKeyName(75, "yache-berry.png");
            this.itemImages.Images.SetKeyName(76, "yellow-apricorn.png");
            this.itemImages.Images.SetKeyName(77, "yellow-flute.png");
            this.itemImages.Images.SetKeyName(78, "stardust.png");
            this.itemImages.Images.SetKeyName(79, "starf-berry.png");
            this.itemImages.Images.SetKeyName(80, "star-piece.png");
            this.itemImages.Images.SetKeyName(81, "steel-gem.png");
            this.itemImages.Images.SetKeyName(82, "steelium-z--bag.png");
            this.itemImages.Images.SetKeyName(83, "steelium-z--held.png");
            this.itemImages.Images.SetKeyName(84, "steelixite.png");
            this.itemImages.Images.SetKeyName(85, "steel-mail.png");
            this.itemImages.Images.SetKeyName(86, "steel-memory.png");
            this.itemImages.Images.SetKeyName(87, "stick.png");
            this.itemImages.Images.SetKeyName(88, "sticky-barb.png");
            this.itemImages.Images.SetKeyName(89, "stone-plate.png");
            this.itemImages.Images.SetKeyName(90, "storage-key.png");
            this.itemImages.Images.SetKeyName(91, "storage-key--galactic-warehouse.png");
            this.itemImages.Images.SetKeyName(92, "storage-key--sea-mauville.png");
            this.itemImages.Images.SetKeyName(93, "strange-souvenir.png");
            this.itemImages.Images.SetKeyName(94, "suite-key.png");
            this.itemImages.Images.SetKeyName(95, "sun-flute.png");
            this.itemImages.Images.SetKeyName(96, "sun-stone.png");
            this.itemImages.Images.SetKeyName(97, "super-potion.png");
            this.itemImages.Images.SetKeyName(98, "super-repel.png");
            this.itemImages.Images.SetKeyName(99, "super-rod.png");
            this.itemImages.Images.SetKeyName(100, "surge-badge.png");
            this.itemImages.Images.SetKeyName(101, "surprise-mulch.png");
            this.itemImages.Images.SetKeyName(102, "swampertite.png");
            this.itemImages.Images.SetKeyName(103, "sweet-heart.png");
            this.itemImages.Images.SetKeyName(104, "swift-wing.png");
            this.itemImages.Images.SetKeyName(105, "tamato-berry.png");
            this.itemImages.Images.SetKeyName(106, "tanga-berry.png");
            this.itemImages.Images.SetKeyName(107, "tapunium-z--bag.png");
            this.itemImages.Images.SetKeyName(108, "tapunium-z--held.png");
            this.itemImages.Images.SetKeyName(109, "tea.png");
            this.itemImages.Images.SetKeyName(110, "teachy-tv.png");
            this.itemImages.Images.SetKeyName(111, "terrain-extender.png");
            this.itemImages.Images.SetKeyName(112, "thanks-mail.png");
            this.itemImages.Images.SetKeyName(113, "thick-club.png");
            this.itemImages.Images.SetKeyName(114, "thunder-stone.png");
            this.itemImages.Images.SetKeyName(115, "tidal-bell.png");
            this.itemImages.Images.SetKeyName(116, "timer-ball.png");
            this.itemImages.Images.SetKeyName(117, "tiny-mushroom.png");
            this.itemImages.Images.SetKeyName(118, "tm-bug.png");
            this.itemImages.Images.SetKeyName(119, "tm-case.png");
            this.itemImages.Images.SetKeyName(120, "tm-dark.png");
            this.itemImages.Images.SetKeyName(121, "tm-dragon.png");
            this.itemImages.Images.SetKeyName(122, "tm-electric.png");
            this.itemImages.Images.SetKeyName(123, "tm-fairy.png");
            this.itemImages.Images.SetKeyName(124, "tm-fighting.png");
            this.itemImages.Images.SetKeyName(125, "tm-fire.png");
            this.itemImages.Images.SetKeyName(126, "tm-flying.png");
            this.itemImages.Images.SetKeyName(127, "tm-ghost.png");
            this.itemImages.Images.SetKeyName(128, "tm-grass.png");
            this.itemImages.Images.SetKeyName(129, "tm-ground.png");
            this.itemImages.Images.SetKeyName(130, "tm-ice.png");
            this.itemImages.Images.SetKeyName(131, "tm-normal.png");
            this.itemImages.Images.SetKeyName(132, "tm-poison.png");
            this.itemImages.Images.SetKeyName(133, "tm-psychic.png");
            this.itemImages.Images.SetKeyName(134, "tm-rock.png");
            this.itemImages.Images.SetKeyName(135, "tm-steel.png");
            this.itemImages.Images.SetKeyName(136, "tmv-pass.png");
            this.itemImages.Images.SetKeyName(137, "tm-water.png");
            this.itemImages.Images.SetKeyName(138, "town-map.png");
            this.itemImages.Images.SetKeyName(139, "toxic-orb.png");
            this.itemImages.Images.SetKeyName(140, "toxic-plate.png");
            this.itemImages.Images.SetKeyName(141, "travel-trunk-gold.png");
            this.itemImages.Images.SetKeyName(142, "travel-trunk-silver.png");
            this.itemImages.Images.SetKeyName(143, "sacred-ash.png");
            this.itemImages.Images.SetKeyName(144, "safari-ball.png");
            this.itemImages.Images.SetKeyName(145, "safety-goggles.png");
            this.itemImages.Images.SetKeyName(146, "sail-fossil.png");
            this.itemImages.Images.SetKeyName(147, "salac-berry.png");
            this.itemImages.Images.SetKeyName(148, "salamencite.png");
            this.itemImages.Images.SetKeyName(149, "sapphire.png");
            this.itemImages.Images.SetKeyName(150, "scanner.png");
            this.itemImages.Images.SetKeyName(151, "sceptilite.png");
            this.itemImages.Images.SetKeyName(152, "scizorite.png");
            this.itemImages.Images.SetKeyName(153, "scope-lens.png");
            this.itemImages.Images.SetKeyName(154, "sea-incense.png");
            this.itemImages.Images.SetKeyName(155, "seal-bag.png");
            this.itemImages.Images.SetKeyName(156, "seal-case.png");
            this.itemImages.Images.SetKeyName(157, "secret-key.png");
            this.itemImages.Images.SetKeyName(158, "secret-potion.png");
            this.itemImages.Images.SetKeyName(159, "shadow-mail.png");
            this.itemImages.Images.SetKeyName(160, "shalour-sable.png");
            this.itemImages.Images.SetKeyName(161, "sharp-beak.png");
            this.itemImages.Images.SetKeyName(162, "sharpedonite.png");
            this.itemImages.Images.SetKeyName(163, "shed-shell.png");
            this.itemImages.Images.SetKeyName(164, "shell-bell.png");
            this.itemImages.Images.SetKeyName(165, "shiny-charm.png");
            this.itemImages.Images.SetKeyName(166, "shiny-stone.png");
            this.itemImages.Images.SetKeyName(167, "shoal-salt.png");
            this.itemImages.Images.SetKeyName(168, "shoal-shell.png");
            this.itemImages.Images.SetKeyName(169, "shock-drive.png");
            this.itemImages.Images.SetKeyName(170, "shuca-berry.png");
            this.itemImages.Images.SetKeyName(171, "silk-scarf.png");
            this.itemImages.Images.SetKeyName(172, "silph-scope.png");
            this.itemImages.Images.SetKeyName(173, "silver-powder.png");
            this.itemImages.Images.SetKeyName(174, "silver-wing.png");
            this.itemImages.Images.SetKeyName(175, "sitrus-berry.png");
            this.itemImages.Images.SetKeyName(176, "skull-fossil.png");
            this.itemImages.Images.SetKeyName(177, "sky-plate.png");
            this.itemImages.Images.SetKeyName(178, "slowbronite.png");
            this.itemImages.Images.SetKeyName(179, "slowpoke-tail.png");
            this.itemImages.Images.SetKeyName(180, "smoke-ball.png");
            this.itemImages.Images.SetKeyName(181, "smooth-rock.png");
            this.itemImages.Images.SetKeyName(182, "snorlium-z--bag.png");
            this.itemImages.Images.SetKeyName(183, "snorlium-z--held.png");
            this.itemImages.Images.SetKeyName(184, "snowball.png");
            this.itemImages.Images.SetKeyName(185, "snow-mail.png");
            this.itemImages.Images.SetKeyName(186, "soda-pop.png");
            this.itemImages.Images.SetKeyName(187, "soft-sand.png");
            this.itemImages.Images.SetKeyName(188, "solganium-z--bag.png");
            this.itemImages.Images.SetKeyName(189, "solganium-z--held.png");
            this.itemImages.Images.SetKeyName(190, "soothe-bell.png");
            this.itemImages.Images.SetKeyName(191, "soot-sack.png");
            this.itemImages.Images.SetKeyName(192, "soul-dew.png");
            this.itemImages.Images.SetKeyName(193, "space-mail.png");
            this.itemImages.Images.SetKeyName(194, "sparkling-stone.png");
            this.itemImages.Images.SetKeyName(195, "spell-tag.png");
            this.itemImages.Images.SetKeyName(196, "spelon-berry.png");
            this.itemImages.Images.SetKeyName(197, "splash-plate.png");
            this.itemImages.Images.SetKeyName(198, "spooky-plate.png");
            this.itemImages.Images.SetKeyName(199, "sport-ball.png");
            this.itemImages.Images.SetKeyName(200, "sprayduck.png");
            this.itemImages.Images.SetKeyName(201, "sprinklotad.png");
            this.itemImages.Images.SetKeyName(202, "squirt-bottle.png");
            this.itemImages.Images.SetKeyName(203, "ss-ticket.png");
            this.itemImages.Images.SetKeyName(204, "ss-ticket--hoenn.png");
            this.itemImages.Images.SetKeyName(205, "stable-mulch.png");
            this.itemImages.Images.SetKeyName(206, "rare-bone.png");
            this.itemImages.Images.SetKeyName(207, "rare-candy.png");
            this.itemImages.Images.SetKeyName(208, "rawst-berry.png");
            this.itemImages.Images.SetKeyName(209, "razor-claw.png");
            this.itemImages.Images.SetKeyName(210, "razor-fang.png");
            this.itemImages.Images.SetKeyName(211, "razz-berry.png");
            this.itemImages.Images.SetKeyName(212, "reaper-cloth.png");
            this.itemImages.Images.SetKeyName(213, "red-apricorn.png");
            this.itemImages.Images.SetKeyName(214, "red-card.png");
            this.itemImages.Images.SetKeyName(215, "red-chain.png");
            this.itemImages.Images.SetKeyName(216, "red-flute.png");
            this.itemImages.Images.SetKeyName(217, "red-nectar.png");
            this.itemImages.Images.SetKeyName(218, "red-orb.png");
            this.itemImages.Images.SetKeyName(219, "red-petal.png");
            this.itemImages.Images.SetKeyName(220, "red-scale.png");
            this.itemImages.Images.SetKeyName(221, "red-scarf.png");
            this.itemImages.Images.SetKeyName(222, "red-shard.png");
            this.itemImages.Images.SetKeyName(223, "relic-band.png");
            this.itemImages.Images.SetKeyName(224, "relic-copper.png");
            this.itemImages.Images.SetKeyName(225, "relic-crown.png");
            this.itemImages.Images.SetKeyName(226, "relic-gold.png");
            this.itemImages.Images.SetKeyName(227, "relic-silver.png");
            this.itemImages.Images.SetKeyName(228, "relic-statue.png");
            this.itemImages.Images.SetKeyName(229, "relic-vase.png");
            this.itemImages.Images.SetKeyName(230, "repeat-ball.png");
            this.itemImages.Images.SetKeyName(231, "repel.png");
            this.itemImages.Images.SetKeyName(232, "reply-mail.png");
            this.itemImages.Images.SetKeyName(233, "reset-urge.png");
            this.itemImages.Images.SetKeyName(234, "resist-wing.png");
            this.itemImages.Images.SetKeyName(235, "retro-mail.png");
            this.itemImages.Images.SetKeyName(236, "reveal-glass.png");
            this.itemImages.Images.SetKeyName(237, "revival-herb.png");
            this.itemImages.Images.SetKeyName(238, "revive.png");
            this.itemImages.Images.SetKeyName(239, "rich-mulch.png");
            this.itemImages.Images.SetKeyName(240, "ride-pager.png");
            this.itemImages.Images.SetKeyName(241, "rindo-berry.png");
            this.itemImages.Images.SetKeyName(242, "ring-target.png");
            this.itemImages.Images.SetKeyName(243, "rm-1-key.png");
            this.itemImages.Images.SetKeyName(244, "rm-2-key.png");
            this.itemImages.Images.SetKeyName(245, "rm-4-key.png");
            this.itemImages.Images.SetKeyName(246, "rm-6-key.png");
            this.itemImages.Images.SetKeyName(247, "rock-gem.png");
            this.itemImages.Images.SetKeyName(248, "rock-incense.png");
            this.itemImages.Images.SetKeyName(249, "rockium-z--bag.png");
            this.itemImages.Images.SetKeyName(250, "rockium-z--held.png");
            this.itemImages.Images.SetKeyName(251, "rock-memory.png");
            this.itemImages.Images.SetKeyName(252, "rocky-helmet.png");
            this.itemImages.Images.SetKeyName(253, "roller-skates.png");
            this.itemImages.Images.SetKeyName(254, "root-fossil.png");
            this.itemImages.Images.SetKeyName(255, "rose-incense.png");
            this.itemImages.Images.SetKeyName(256, "roseli-berry.png");
            this.itemImages.Images.SetKeyName(257, "roto-bargain.png");
            this.itemImages.Images.SetKeyName(258, "roto-boost.png");
            this.itemImages.Images.SetKeyName(259, "roto-catch.png");
            this.itemImages.Images.SetKeyName(260, "roto-encounter.png");
            this.itemImages.Images.SetKeyName(261, "roto-exp-points.png");
            this.itemImages.Images.SetKeyName(262, "roto-friendship.png");
            this.itemImages.Images.SetKeyName(263, "roto-hatch.png");
            this.itemImages.Images.SetKeyName(264, "roto-hp-restore.png");
            this.itemImages.Images.SetKeyName(265, "roto-pp-restore.png");
            this.itemImages.Images.SetKeyName(266, "roto-prize-money.png");
            this.itemImages.Images.SetKeyName(267, "roto-stealth.png");
            this.itemImages.Images.SetKeyName(268, "rowap-berry.png");
            this.itemImages.Images.SetKeyName(269, "rsvp-mail.png");
            this.itemImages.Images.SetKeyName(270, "ruby.png");
            this.itemImages.Images.SetKeyName(271, "rule-book.png");
            this.itemImages.Images.SetKeyName(272, "sablenite.png");
            this.itemImages.Images.SetKeyName(273, "sachet.png");
            this.itemImages.Images.SetKeyName(274, "photo-album.png");
            this.itemImages.Images.SetKeyName(275, "pidgeotite.png");
            this.itemImages.Images.SetKeyName(276, "pikanium-z--bag.png");
            this.itemImages.Images.SetKeyName(277, "pikanium-z--held.png");
            this.itemImages.Images.SetKeyName(278, "pikashunium-z--bag.png");
            this.itemImages.Images.SetKeyName(279, "pikashunium-z--held.png");
            this.itemImages.Images.SetKeyName(280, "pinap-berry.png");
            this.itemImages.Images.SetKeyName(281, "pink-apricorn.png");
            this.itemImages.Images.SetKeyName(282, "pink-nectar.png");
            this.itemImages.Images.SetKeyName(283, "pink-petal.png");
            this.itemImages.Images.SetKeyName(284, "pink-scarf.png");
            this.itemImages.Images.SetKeyName(285, "pinsirite.png");
            this.itemImages.Images.SetKeyName(286, "pixie-plate.png");
            this.itemImages.Images.SetKeyName(287, "plasma-card.png");
            this.itemImages.Images.SetKeyName(288, "plume-fossil.png");
            this.itemImages.Images.SetKeyName(289, "poffin-case.png");
            this.itemImages.Images.SetKeyName(290, "point-card.png");
            this.itemImages.Images.SetKeyName(291, "poison-barb.png");
            this.itemImages.Images.SetKeyName(292, "poison-gem.png");
            this.itemImages.Images.SetKeyName(293, "poisonium-z--bag.png");
            this.itemImages.Images.SetKeyName(294, "poisonium-z--held.png");
            this.itemImages.Images.SetKeyName(295, "poison-memory.png");
            this.itemImages.Images.SetKeyName(296, "poke-ball.png");
            this.itemImages.Images.SetKeyName(297, "pokeblock-case.png");
            this.itemImages.Images.SetKeyName(298, "pokeblock-kit.png");
            this.itemImages.Images.SetKeyName(299, "poke-doll.png");
            this.itemImages.Images.SetKeyName(300, "poke-flute.png");
            this.itemImages.Images.SetKeyName(301, "poke-radar.png");
            this.itemImages.Images.SetKeyName(302, "poke-toy.png");
            this.itemImages.Images.SetKeyName(303, "pomeg-berry.png");
            this.itemImages.Images.SetKeyName(304, "potion.png");
            this.itemImages.Images.SetKeyName(305, "powder-jar.png");
            this.itemImages.Images.SetKeyName(306, "power-anklet.png");
            this.itemImages.Images.SetKeyName(307, "power-band.png");
            this.itemImages.Images.SetKeyName(308, "power-belt.png");
            this.itemImages.Images.SetKeyName(309, "power-bracer.png");
            this.itemImages.Images.SetKeyName(310, "power-herb.png");
            this.itemImages.Images.SetKeyName(311, "power-lens.png");
            this.itemImages.Images.SetKeyName(312, "power-plant-pass.png");
            this.itemImages.Images.SetKeyName(313, "power-weight.png");
            this.itemImages.Images.SetKeyName(314, "pp-max.png");
            this.itemImages.Images.SetKeyName(315, "pp-up.png");
            this.itemImages.Images.SetKeyName(316, "premier-ball.png");
            this.itemImages.Images.SetKeyName(317, "pretty-wing.png");
            this.itemImages.Images.SetKeyName(318, "primarium-z--bag.png");
            this.itemImages.Images.SetKeyName(319, "primarium-z--held.png");
            this.itemImages.Images.SetKeyName(320, "prism-scale.png");
            this.itemImages.Images.SetKeyName(321, "prison-bottle.png");
            this.itemImages.Images.SetKeyName(322, "professors-mask.png");
            this.itemImages.Images.SetKeyName(323, "profs-letter.png");
            this.itemImages.Images.SetKeyName(324, "prop-case.png");
            this.itemImages.Images.SetKeyName(325, "protective-pads.png");
            this.itemImages.Images.SetKeyName(326, "protector.png");
            this.itemImages.Images.SetKeyName(327, "protein.png");
            this.itemImages.Images.SetKeyName(328, "psychic-gem.png");
            this.itemImages.Images.SetKeyName(329, "psychic-memory.png");
            this.itemImages.Images.SetKeyName(330, "psychic-seed.png");
            this.itemImages.Images.SetKeyName(331, "psychium-z--bag.png");
            this.itemImages.Images.SetKeyName(332, "psychium-z--held.png");
            this.itemImages.Images.SetKeyName(333, "pure-incense.png");
            this.itemImages.Images.SetKeyName(334, "purple-nectar.png");
            this.itemImages.Images.SetKeyName(335, "purple-petal.png");
            this.itemImages.Images.SetKeyName(336, "qualot-berry.png");
            this.itemImages.Images.SetKeyName(337, "quick-ball.png");
            this.itemImages.Images.SetKeyName(338, "quick-claw.png");
            this.itemImages.Images.SetKeyName(339, "quick-powder.png");
            this.itemImages.Images.SetKeyName(340, "rabuta-berry.png");
            this.itemImages.Images.SetKeyName(341, "rage-candy-bar.png");
            this.itemImages.Images.SetKeyName(342, "rainbow-flower.png");
            this.itemImages.Images.SetKeyName(343, "rainbow-pass.png");
            this.itemImages.Images.SetKeyName(344, "rainbow-wing.png");
            this.itemImages.Images.SetKeyName(345, "meteorite.png");
            this.itemImages.Images.SetKeyName(346, "meteorite--3.png");
            this.itemImages.Images.SetKeyName(347, "meteorite--4.png");
            this.itemImages.Images.SetKeyName(348, "meteorite-shard.png");
            this.itemImages.Images.SetKeyName(349, "metronome.png");
            this.itemImages.Images.SetKeyName(350, "mewnium-z--bag.png");
            this.itemImages.Images.SetKeyName(351, "mewnium-z--held.png");
            this.itemImages.Images.SetKeyName(352, "mewtwonite-x.png");
            this.itemImages.Images.SetKeyName(353, "mewtwonite-y.png");
            this.itemImages.Images.SetKeyName(354, "micle-berry.png");
            this.itemImages.Images.SetKeyName(355, "mimikium-z--bag.png");
            this.itemImages.Images.SetKeyName(356, "mimikium-z--held.png");
            this.itemImages.Images.SetKeyName(357, "mind-plate.png");
            this.itemImages.Images.SetKeyName(358, "miracle-seed.png");
            this.itemImages.Images.SetKeyName(359, "misty-seed.png");
            this.itemImages.Images.SetKeyName(360, "moomoo-milk.png");
            this.itemImages.Images.SetKeyName(361, "moon-ball.png");
            this.itemImages.Images.SetKeyName(362, "moon-flute.png");
            this.itemImages.Images.SetKeyName(363, "moon-stone.png");
            this.itemImages.Images.SetKeyName(364, "mosaic-mail.png");
            this.itemImages.Images.SetKeyName(365, "muscle-band.png");
            this.itemImages.Images.SetKeyName(366, "muscle-wing.png");
            this.itemImages.Images.SetKeyName(367, "mystery-egg.png");
            this.itemImages.Images.SetKeyName(368, "mysticticket.png");
            this.itemImages.Images.SetKeyName(369, "mystic-water.png");
            this.itemImages.Images.SetKeyName(370, "nanab-berry.png");
            this.itemImages.Images.SetKeyName(371, "nest-ball.png");
            this.itemImages.Images.SetKeyName(372, "net-ball.png");
            this.itemImages.Images.SetKeyName(373, "never-melt-ice.png");
            this.itemImages.Images.SetKeyName(374, "n-lunarizer--merge.png");
            this.itemImages.Images.SetKeyName(375, "n-lunarizer--split.png");
            this.itemImages.Images.SetKeyName(376, "nomel-berry.png");
            this.itemImages.Images.SetKeyName(377, "normal-gem.png");
            this.itemImages.Images.SetKeyName(378, "normalium-z--bag.png");
            this.itemImages.Images.SetKeyName(379, "normalium-z--held.png");
            this.itemImages.Images.SetKeyName(380, "n-solarizer--merge.png");
            this.itemImages.Images.SetKeyName(381, "n-solarizer--split.png");
            this.itemImages.Images.SetKeyName(382, "nugget.png");
            this.itemImages.Images.SetKeyName(383, "oaks-letter.png");
            this.itemImages.Images.SetKeyName(384, "oaks-parcel.png");
            this.itemImages.Images.SetKeyName(385, "occa-berry.png");
            this.itemImages.Images.SetKeyName(386, "odd-incense.png");
            this.itemImages.Images.SetKeyName(387, "odd-keystone.png");
            this.itemImages.Images.SetKeyName(388, "old-amber.png");
            this.itemImages.Images.SetKeyName(389, "old-charm.png");
            this.itemImages.Images.SetKeyName(390, "old-gateau.png");
            this.itemImages.Images.SetKeyName(391, "old-rod.png");
            this.itemImages.Images.SetKeyName(392, "old-sea-map.png");
            this.itemImages.Images.SetKeyName(393, "oran-berry.png");
            this.itemImages.Images.SetKeyName(394, "orange-mail.png");
            this.itemImages.Images.SetKeyName(395, "orange-petal.png");
            this.itemImages.Images.SetKeyName(396, "oval-charm.png");
            this.itemImages.Images.SetKeyName(397, "oval-stone.png");
            this.itemImages.Images.SetKeyName(398, "pair-of-tickets.png");
            this.itemImages.Images.SetKeyName(399, "pal-pad.png");
            this.itemImages.Images.SetKeyName(400, "pamtre-berry.png");
            this.itemImages.Images.SetKeyName(401, "paralyze-heal.png");
            this.itemImages.Images.SetKeyName(402, "parcel.png");
            this.itemImages.Images.SetKeyName(403, "park-ball.png");
            this.itemImages.Images.SetKeyName(404, "pass.png");
            this.itemImages.Images.SetKeyName(405, "passho-berry.png");
            this.itemImages.Images.SetKeyName(406, "pass-orb.png");
            this.itemImages.Images.SetKeyName(407, "payapa-berry.png");
            this.itemImages.Images.SetKeyName(408, "pearl.png");
            this.itemImages.Images.SetKeyName(409, "pearl-string.png");
            this.itemImages.Images.SetKeyName(410, "pecha-berry.png");
            this.itemImages.Images.SetKeyName(411, "permit.png");
            this.itemImages.Images.SetKeyName(412, "persim-berry.png");
            this.itemImages.Images.SetKeyName(413, "petaya-berry.png");
            this.itemImages.Images.SetKeyName(414, "lift-key.png");
            this.itemImages.Images.SetKeyName(415, "light-ball.png");
            this.itemImages.Images.SetKeyName(416, "light-clay.png");
            this.itemImages.Images.SetKeyName(417, "light-stone.png");
            this.itemImages.Images.SetKeyName(418, "like-mail.png");
            this.itemImages.Images.SetKeyName(419, "lock-capsule.png");
            this.itemImages.Images.SetKeyName(420, "looker-ticket.png");
            this.itemImages.Images.SetKeyName(421, "loot-sack.png");
            this.itemImages.Images.SetKeyName(422, "lopunnite.png");
            this.itemImages.Images.SetKeyName(423, "lost-item.png");
            this.itemImages.Images.SetKeyName(424, "love-ball.png");
            this.itemImages.Images.SetKeyName(425, "lucarionite.png");
            this.itemImages.Images.SetKeyName(426, "luck-incense.png");
            this.itemImages.Images.SetKeyName(427, "lucky-egg.png");
            this.itemImages.Images.SetKeyName(428, "lucky-punch.png");
            this.itemImages.Images.SetKeyName(429, "lum-berry.png");
            this.itemImages.Images.SetKeyName(430, "luminous-moss.png");
            this.itemImages.Images.SetKeyName(431, "lumiose-galette.png");
            this.itemImages.Images.SetKeyName(432, "lunalium-z--bag.png");
            this.itemImages.Images.SetKeyName(433, "lunalium-z--held.png");
            this.itemImages.Images.SetKeyName(434, "lunar-wing.png");
            this.itemImages.Images.SetKeyName(435, "lure-ball.png");
            this.itemImages.Images.SetKeyName(436, "lustrous-orb.png");
            this.itemImages.Images.SetKeyName(437, "luxury-ball.png");
            this.itemImages.Images.SetKeyName(438, "lycanium-z--bag.png");
            this.itemImages.Images.SetKeyName(439, "lycanium-z--held.png");
            this.itemImages.Images.SetKeyName(440, "mach-bike.png");
            this.itemImages.Images.SetKeyName(441, "machine-part.png");
            this.itemImages.Images.SetKeyName(442, "macho-brace.png");
            this.itemImages.Images.SetKeyName(443, "magma-emblem.png");
            this.itemImages.Images.SetKeyName(444, "magmarizer.png");
            this.itemImages.Images.SetKeyName(445, "magma-stone.png");
            this.itemImages.Images.SetKeyName(446, "magma-suit.png");
            this.itemImages.Images.SetKeyName(447, "magnet.png");
            this.itemImages.Images.SetKeyName(448, "mago-berry.png");
            this.itemImages.Images.SetKeyName(449, "magost-berry.png");
            this.itemImages.Images.SetKeyName(450, "makeup-bag.png");
            this.itemImages.Images.SetKeyName(451, "manectite.png");
            this.itemImages.Images.SetKeyName(452, "maranga-berry.png");
            this.itemImages.Images.SetKeyName(453, "marshadium-z--bag.png");
            this.itemImages.Images.SetKeyName(454, "marshadium-z--held.png");
            this.itemImages.Images.SetKeyName(455, "master-ball.png");
            this.itemImages.Images.SetKeyName(456, "mawilite.png");
            this.itemImages.Images.SetKeyName(457, "max-elixir.png");
            this.itemImages.Images.SetKeyName(458, "max-ether.png");
            this.itemImages.Images.SetKeyName(459, "max-potion.png");
            this.itemImages.Images.SetKeyName(460, "max-repel.png");
            this.itemImages.Images.SetKeyName(461, "max-revive.png");
            this.itemImages.Images.SetKeyName(462, "meadow-plate.png");
            this.itemImages.Images.SetKeyName(463, "mech-mail.png");
            this.itemImages.Images.SetKeyName(464, "medal-box.png");
            this.itemImages.Images.SetKeyName(465, "medichamite.png");
            this.itemImages.Images.SetKeyName(466, "mega-anchor.png");
            this.itemImages.Images.SetKeyName(467, "mega-anklet.png");
            this.itemImages.Images.SetKeyName(468, "mega-bracelet.png");
            this.itemImages.Images.SetKeyName(469, "mega-charm.png");
            this.itemImages.Images.SetKeyName(470, "mega-cuff.png");
            this.itemImages.Images.SetKeyName(471, "mega-glasses.png");
            this.itemImages.Images.SetKeyName(472, "mega-glove.png");
            this.itemImages.Images.SetKeyName(473, "mega-pendant.png");
            this.itemImages.Images.SetKeyName(474, "mega-ring.png");
            this.itemImages.Images.SetKeyName(475, "mega-stickpin.png");
            this.itemImages.Images.SetKeyName(476, "mega-tiara.png");
            this.itemImages.Images.SetKeyName(477, "member-card.png");
            this.itemImages.Images.SetKeyName(478, "mental-herb.png");
            this.itemImages.Images.SetKeyName(479, "metagrossite.png");
            this.itemImages.Images.SetKeyName(480, "metal-coat.png");
            this.itemImages.Images.SetKeyName(481, "metal-powder.png");
            this.itemImages.Images.SetKeyName(482, "meteorite--2.png");
            this.itemImages.Images.SetKeyName(483, "hm04.png");
            this.itemImages.Images.SetKeyName(484, "hm05.png");
            this.itemImages.Images.SetKeyName(485, "hm06.png");
            this.itemImages.Images.SetKeyName(486, "hm07.png");
            this.itemImages.Images.SetKeyName(487, "holo-caster.png");
            this.itemImages.Images.SetKeyName(488, "holo-caster-green.png");
            this.itemImages.Images.SetKeyName(489, "holo-caster--green.png");
            this.itemImages.Images.SetKeyName(490, "holo-caster-red.png");
            this.itemImages.Images.SetKeyName(491, "holo-caster--red.png");
            this.itemImages.Images.SetKeyName(492, "hondew-berry.png");
            this.itemImages.Images.SetKeyName(493, "honey.png");
            this.itemImages.Images.SetKeyName(494, "honor-of-kalos.png");
            this.itemImages.Images.SetKeyName(495, "houndoominite.png");
            this.itemImages.Images.SetKeyName(496, "hp-up.png");
            this.itemImages.Images.SetKeyName(497, "hyper-potion.png");
            this.itemImages.Images.SetKeyName(498, "iapapa-berry.png");
            this.itemImages.Images.SetKeyName(499, "ice-gem.png");
            this.itemImages.Images.SetKeyName(500, "ice-heal.png");
            this.itemImages.Images.SetKeyName(501, "ice-memory.png");
            this.itemImages.Images.SetKeyName(502, "ice-stone.png");
            this.itemImages.Images.SetKeyName(503, "icicle-plate.png");
            this.itemImages.Images.SetKeyName(504, "icium-z--bag.png");
            this.itemImages.Images.SetKeyName(505, "icium-z--held.png");
            this.itemImages.Images.SetKeyName(506, "icy-rock.png");
            this.itemImages.Images.SetKeyName(507, "ilimas-normalium-z.png");
            this.itemImages.Images.SetKeyName(508, "incinium-z--bag.png");
            this.itemImages.Images.SetKeyName(509, "incinium-z--held.png");
            this.itemImages.Images.SetKeyName(510, "inquiry-mail.png");
            this.itemImages.Images.SetKeyName(511, "insect-plate.png");
            this.itemImages.Images.SetKeyName(512, "intriguing-stone.png");
            this.itemImages.Images.SetKeyName(513, "iron.png");
            this.itemImages.Images.SetKeyName(514, "iron-ball.png");
            this.itemImages.Images.SetKeyName(515, "iron-plate.png");
            this.itemImages.Images.SetKeyName(516, "item-drop.png");
            this.itemImages.Images.SetKeyName(517, "item-urge.png");
            this.itemImages.Images.SetKeyName(518, "jaboca-berry.png");
            this.itemImages.Images.SetKeyName(519, "jade-orb.png");
            this.itemImages.Images.SetKeyName(520, "jaw-fossil.png");
            this.itemImages.Images.SetKeyName(521, "journal.png");
            this.itemImages.Images.SetKeyName(522, "kangaskhanite.png");
            this.itemImages.Images.SetKeyName(523, "kasib-berry.png");
            this.itemImages.Images.SetKeyName(524, "kebia-berry.png");
            this.itemImages.Images.SetKeyName(525, "kee-berry.png");
            this.itemImages.Images.SetKeyName(526, "kelpsy-berry.png");
            this.itemImages.Images.SetKeyName(527, "key-stone.png");
            this.itemImages.Images.SetKeyName(528, "key-to-room-1.png");
            this.itemImages.Images.SetKeyName(529, "key-to-room-2.png");
            this.itemImages.Images.SetKeyName(530, "key-to-room-4.png");
            this.itemImages.Images.SetKeyName(531, "key-to-room-6.png");
            this.itemImages.Images.SetKeyName(532, "kings-rock.png");
            this.itemImages.Images.SetKeyName(533, "kommonium-z--bag.png");
            this.itemImages.Images.SetKeyName(534, "kommonium-z--held.png");
            this.itemImages.Images.SetKeyName(535, "lagging-tail.png");
            this.itemImages.Images.SetKeyName(536, "lansat-berry.png");
            this.itemImages.Images.SetKeyName(537, "latiasite.png");
            this.itemImages.Images.SetKeyName(538, "latiosite.png");
            this.itemImages.Images.SetKeyName(539, "lava-cookie.png");
            this.itemImages.Images.SetKeyName(540, "lax-incense.png");
            this.itemImages.Images.SetKeyName(541, "leaf-stone.png");
            this.itemImages.Images.SetKeyName(542, "leftovers.png");
            this.itemImages.Images.SetKeyName(543, "left-poke-ball.png");
            this.itemImages.Images.SetKeyName(544, "lemonade.png");
            this.itemImages.Images.SetKeyName(545, "lens-case.png");
            this.itemImages.Images.SetKeyName(546, "leppa-berry.png");
            this.itemImages.Images.SetKeyName(547, "letter.png");
            this.itemImages.Images.SetKeyName(548, "level-ball.png");
            this.itemImages.Images.SetKeyName(549, "liberty-pass.png");
            this.itemImages.Images.SetKeyName(550, "liechi-berry.png");
            this.itemImages.Images.SetKeyName(551, "life-orb.png");
            this.itemImages.Images.SetKeyName(552, "full-heal.png");
            this.itemImages.Images.SetKeyName(553, "full-incense.png");
            this.itemImages.Images.SetKeyName(554, "full-restore.png");
            this.itemImages.Images.SetKeyName(555, "galactic-key.png");
            this.itemImages.Images.SetKeyName(556, "galladite.png");
            this.itemImages.Images.SetKeyName(557, "ganlon-berry.png");
            this.itemImages.Images.SetKeyName(558, "garchompite.png");
            this.itemImages.Images.SetKeyName(559, "gardevoirite.png");
            this.itemImages.Images.SetKeyName(560, "gb-sounds.png");
            this.itemImages.Images.SetKeyName(561, "gengarite.png");
            this.itemImages.Images.SetKeyName(562, "genius-wing.png");
            this.itemImages.Images.SetKeyName(563, "ghost-gem.png");
            this.itemImages.Images.SetKeyName(564, "ghostium-z--bag.png");
            this.itemImages.Images.SetKeyName(565, "ghostium-z--held.png");
            this.itemImages.Images.SetKeyName(566, "ghost-memory.png");
            this.itemImages.Images.SetKeyName(567, "glalitite.png");
            this.itemImages.Images.SetKeyName(568, "glitter-mail.png");
            this.itemImages.Images.SetKeyName(569, "god-stone.png");
            this.itemImages.Images.SetKeyName(570, "go-goggles.png");
            this.itemImages.Images.SetKeyName(571, "gold-bottle-cap.png");
            this.itemImages.Images.SetKeyName(572, "gold-teeth.png");
            this.itemImages.Images.SetKeyName(573, "good-rod.png");
            this.itemImages.Images.SetKeyName(574, "gooey-mulch.png");
            this.itemImages.Images.SetKeyName(575, "gracidea.png");
            this.itemImages.Images.SetKeyName(576, "gram-1.png");
            this.itemImages.Images.SetKeyName(577, "gram-2.png");
            this.itemImages.Images.SetKeyName(578, "gram-3.png");
            this.itemImages.Images.SetKeyName(579, "grass-gem.png");
            this.itemImages.Images.SetKeyName(580, "grassium-z--bag.png");
            this.itemImages.Images.SetKeyName(581, "grassium-z--held.png");
            this.itemImages.Images.SetKeyName(582, "grass-mail.png");
            this.itemImages.Images.SetKeyName(583, "grass-memory.png");
            this.itemImages.Images.SetKeyName(584, "grassy-seed.png");
            this.itemImages.Images.SetKeyName(585, "great-ball.png");
            this.itemImages.Images.SetKeyName(586, "green-apricorn.png");
            this.itemImages.Images.SetKeyName(587, "green-petal.png");
            this.itemImages.Images.SetKeyName(588, "green-scarf.png");
            this.itemImages.Images.SetKeyName(589, "green-shard.png");
            this.itemImages.Images.SetKeyName(590, "greet-mail.png");
            this.itemImages.Images.SetKeyName(591, "grepa-berry.png");
            this.itemImages.Images.SetKeyName(592, "grip-claw.png");
            this.itemImages.Images.SetKeyName(593, "griseous-orb.png");
            this.itemImages.Images.SetKeyName(594, "ground-gem.png");
            this.itemImages.Images.SetKeyName(595, "groundium-z--bag.png");
            this.itemImages.Images.SetKeyName(596, "groundium-z--held.png");
            this.itemImages.Images.SetKeyName(597, "ground-memory.png");
            this.itemImages.Images.SetKeyName(598, "growth-mulch.png");
            this.itemImages.Images.SetKeyName(599, "grubby-hanky.png");
            this.itemImages.Images.SetKeyName(600, "guard-spec.png");
            this.itemImages.Images.SetKeyName(601, "gyaradosite.png");
            this.itemImages.Images.SetKeyName(602, "haban-berry.png");
            this.itemImages.Images.SetKeyName(603, "harbor-mail.png");
            this.itemImages.Images.SetKeyName(604, "hard-stone.png");
            this.itemImages.Images.SetKeyName(605, "heal-ball.png");
            this.itemImages.Images.SetKeyName(606, "heal-powder.png");
            this.itemImages.Images.SetKeyName(607, "health-wing.png");
            this.itemImages.Images.SetKeyName(608, "heart-mail.png");
            this.itemImages.Images.SetKeyName(609, "heart-scale.png");
            this.itemImages.Images.SetKeyName(610, "heat-rock.png");
            this.itemImages.Images.SetKeyName(611, "heavy-ball.png");
            this.itemImages.Images.SetKeyName(612, "helix-fossil.png");
            this.itemImages.Images.SetKeyName(613, "heracronite.png");
            this.itemImages.Images.SetKeyName(614, "hm01.png");
            this.itemImages.Images.SetKeyName(615, "hm02.png");
            this.itemImages.Images.SetKeyName(616, "hm03.png");
            this.itemImages.Images.SetKeyName(617, "hm-fighting.png");
            this.itemImages.Images.SetKeyName(618, "hm-flying.png");
            this.itemImages.Images.SetKeyName(619, "hm-normal.png");
            this.itemImages.Images.SetKeyName(620, "hm-water.png");
            this.itemImages.Images.SetKeyName(621, "dropped-item.png");
            this.itemImages.Images.SetKeyName(622, "dropped-item-red.png");
            this.itemImages.Images.SetKeyName(623, "dropped-item-yellow.png");
            this.itemImages.Images.SetKeyName(624, "dropped-item--yellow.png");
            this.itemImages.Images.SetKeyName(625, "dubious-disc.png");
            this.itemImages.Images.SetKeyName(626, "durin-berry.png");
            this.itemImages.Images.SetKeyName(627, "dusk-ball.png");
            this.itemImages.Images.SetKeyName(628, "dusk-stone.png");
            this.itemImages.Images.SetKeyName(629, "earth-plate.png");
            this.itemImages.Images.SetKeyName(630, "eevium-z--bag.png");
            this.itemImages.Images.SetKeyName(631, "eevium-z--held.png");
            this.itemImages.Images.SetKeyName(632, "eject-button.png");
            this.itemImages.Images.SetKeyName(633, "electirizer.png");
            this.itemImages.Images.SetKeyName(634, "electric-gem.png");
            this.itemImages.Images.SetKeyName(635, "electric-memory.png");
            this.itemImages.Images.SetKeyName(636, "electric-seed.png");
            this.itemImages.Images.SetKeyName(637, "electrium-z--bag.png");
            this.itemImages.Images.SetKeyName(638, "electrium-z--held.png");
            this.itemImages.Images.SetKeyName(639, "elevator-key.png");
            this.itemImages.Images.SetKeyName(640, "elixir.png");
            this.itemImages.Images.SetKeyName(641, "energy-powder.png");
            this.itemImages.Images.SetKeyName(642, "energy-root.png");
            this.itemImages.Images.SetKeyName(643, "enigma-berry.png");
            this.itemImages.Images.SetKeyName(644, "enigma-stone.png");
            this.itemImages.Images.SetKeyName(645, "enigmatic-card.png");
            this.itemImages.Images.SetKeyName(646, "eon-flute.png");
            this.itemImages.Images.SetKeyName(647, "eon-ticket.png");
            this.itemImages.Images.SetKeyName(648, "escape-rope.png");
            this.itemImages.Images.SetKeyName(649, "ether.png");
            this.itemImages.Images.SetKeyName(650, "everstone.png");
            this.itemImages.Images.SetKeyName(651, "eviolite.png");
            this.itemImages.Images.SetKeyName(652, "expert-belt.png");
            this.itemImages.Images.SetKeyName(653, "explorer-kit.png");
            this.itemImages.Images.SetKeyName(654, "exp-share.png");
            this.itemImages.Images.SetKeyName(655, "fab-mail.png");
            this.itemImages.Images.SetKeyName(656, "fairium-z--bag.png");
            this.itemImages.Images.SetKeyName(657, "fairium-z--held.png");
            this.itemImages.Images.SetKeyName(658, "fairy-gem.png");
            this.itemImages.Images.SetKeyName(659, "fairy-memory.png");
            this.itemImages.Images.SetKeyName(660, "fame-checker.png");
            this.itemImages.Images.SetKeyName(661, "fashion-case.png");
            this.itemImages.Images.SetKeyName(662, "fast-ball.png");
            this.itemImages.Images.SetKeyName(663, "favored-mail.png");
            this.itemImages.Images.SetKeyName(664, "festival-ticket.png");
            this.itemImages.Images.SetKeyName(665, "fighting-gem.png");
            this.itemImages.Images.SetKeyName(666, "fighting-memory.png");
            this.itemImages.Images.SetKeyName(667, "fightinium-z--bag.png");
            this.itemImages.Images.SetKeyName(668, "fightinium-z--held.png");
            this.itemImages.Images.SetKeyName(669, "figy-berry.png");
            this.itemImages.Images.SetKeyName(670, "fire-gem.png");
            this.itemImages.Images.SetKeyName(671, "fire-memory.png");
            this.itemImages.Images.SetKeyName(672, "fire-stone.png");
            this.itemImages.Images.SetKeyName(673, "firium-z--bag.png");
            this.itemImages.Images.SetKeyName(674, "firium-z--held.png");
            this.itemImages.Images.SetKeyName(675, "fishing-rod.png");
            this.itemImages.Images.SetKeyName(676, "fist-plate.png");
            this.itemImages.Images.SetKeyName(677, "flame-mail.png");
            this.itemImages.Images.SetKeyName(678, "flame-orb.png");
            this.itemImages.Images.SetKeyName(679, "flame-plate.png");
            this.itemImages.Images.SetKeyName(680, "float-stone.png");
            this.itemImages.Images.SetKeyName(681, "fluffy-tail.png");
            this.itemImages.Images.SetKeyName(682, "flying-gem.png");
            this.itemImages.Images.SetKeyName(683, "flying-memory.png");
            this.itemImages.Images.SetKeyName(684, "flyinium-z--bag.png");
            this.itemImages.Images.SetKeyName(685, "flyinium-z--held.png");
            this.itemImages.Images.SetKeyName(686, "focus-band.png");
            this.itemImages.Images.SetKeyName(687, "focus-sash.png");
            this.itemImages.Images.SetKeyName(688, "forage-bag.png");
            this.itemImages.Images.SetKeyName(689, "fresh-water.png");
            this.itemImages.Images.SetKeyName(690, "friend-ball.png");
            this.itemImages.Images.SetKeyName(691, "custap-berry.png");
            this.itemImages.Images.SetKeyName(692, "damp-mulch.png");
            this.itemImages.Images.SetKeyName(693, "damp-rock.png");
            this.itemImages.Images.SetKeyName(694, "dark-gem.png");
            this.itemImages.Images.SetKeyName(695, "darkinium-z--bag.png");
            this.itemImages.Images.SetKeyName(696, "darkinium-z--held.png");
            this.itemImages.Images.SetKeyName(697, "dark-memory.png");
            this.itemImages.Images.SetKeyName(698, "dark-stone.png");
            this.itemImages.Images.SetKeyName(699, "data-card.png");
            this.itemImages.Images.SetKeyName(700, "data-card-01.png");
            this.itemImages.Images.SetKeyName(701, "data-card-02.png");
            this.itemImages.Images.SetKeyName(702, "data-card-03.png");
            this.itemImages.Images.SetKeyName(703, "data-card-04.png");
            this.itemImages.Images.SetKeyName(704, "data-card-05.png");
            this.itemImages.Images.SetKeyName(705, "data-card-06.png");
            this.itemImages.Images.SetKeyName(706, "data-card-07.png");
            this.itemImages.Images.SetKeyName(707, "data-card-08.png");
            this.itemImages.Images.SetKeyName(708, "data-card-09.png");
            this.itemImages.Images.SetKeyName(709, "data-card-10.png");
            this.itemImages.Images.SetKeyName(710, "data-card-11.png");
            this.itemImages.Images.SetKeyName(711, "data-card-12.png");
            this.itemImages.Images.SetKeyName(712, "data-card-13.png");
            this.itemImages.Images.SetKeyName(713, "data-card-14.png");
            this.itemImages.Images.SetKeyName(714, "data-card-15.png");
            this.itemImages.Images.SetKeyName(715, "data-card-16.png");
            this.itemImages.Images.SetKeyName(716, "data-card-17.png");
            this.itemImages.Images.SetKeyName(717, "data-card-18.png");
            this.itemImages.Images.SetKeyName(718, "data-card-19.png");
            this.itemImages.Images.SetKeyName(719, "data-card-20.png");
            this.itemImages.Images.SetKeyName(720, "data-card-21.png");
            this.itemImages.Images.SetKeyName(721, "data-card-22.png");
            this.itemImages.Images.SetKeyName(722, "data-card-23.png");
            this.itemImages.Images.SetKeyName(723, "data-card-24.png");
            this.itemImages.Images.SetKeyName(724, "data-card-25.png");
            this.itemImages.Images.SetKeyName(725, "data-card-26.png");
            this.itemImages.Images.SetKeyName(726, "data-card-27.png");
            this.itemImages.Images.SetKeyName(727, "dawn-stone.png");
            this.itemImages.Images.SetKeyName(728, "decidium-z--bag.png");
            this.itemImages.Images.SetKeyName(729, "decidium-z--held.png");
            this.itemImages.Images.SetKeyName(730, "deep-sea-scale.png");
            this.itemImages.Images.SetKeyName(731, "deep-sea-tooth.png");
            this.itemImages.Images.SetKeyName(732, "destiny-knot.png");
            this.itemImages.Images.SetKeyName(733, "devon-goods.png");
            this.itemImages.Images.SetKeyName(734, "devon-parts.png");
            this.itemImages.Images.SetKeyName(735, "devon-scope.png");
            this.itemImages.Images.SetKeyName(736, "devon-scuba-gear.png");
            this.itemImages.Images.SetKeyName(737, "diancite.png");
            this.itemImages.Images.SetKeyName(738, "dire-hit.png");
            this.itemImages.Images.SetKeyName(739, "dire-hit-2.png");
            this.itemImages.Images.SetKeyName(740, "dire-hit-3.png");
            this.itemImages.Images.SetKeyName(741, "discount-coupon.png");
            this.itemImages.Images.SetKeyName(742, "dive-ball.png");
            this.itemImages.Images.SetKeyName(743, "dna-splicers.png");
            this.itemImages.Images.SetKeyName(744, "dna-splicers--merge.png");
            this.itemImages.Images.SetKeyName(745, "dna-splicers--split.png");
            this.itemImages.Images.SetKeyName(746, "dome-fossil.png");
            this.itemImages.Images.SetKeyName(747, "douse-drive.png");
            this.itemImages.Images.SetKeyName(748, "dowsing-machine.png");
            this.itemImages.Images.SetKeyName(749, "draco-plate.png");
            this.itemImages.Images.SetKeyName(750, "dragon-fang.png");
            this.itemImages.Images.SetKeyName(751, "dragon-gem.png");
            this.itemImages.Images.SetKeyName(752, "dragonium-z--bag.png");
            this.itemImages.Images.SetKeyName(753, "dragonium-z--held.png");
            this.itemImages.Images.SetKeyName(754, "dragon-memory.png");
            this.itemImages.Images.SetKeyName(755, "dragon-scale.png");
            this.itemImages.Images.SetKeyName(756, "dragon-skull.png");
            this.itemImages.Images.SetKeyName(757, "dread-plate.png");
            this.itemImages.Images.SetKeyName(758, "dream-ball.png");
            this.itemImages.Images.SetKeyName(759, "dream-mail.png");
            this.itemImages.Images.SetKeyName(760, "dropped-item--red.png");
            this.itemImages.Images.SetKeyName(761, "black-flute.png");
            this.itemImages.Images.SetKeyName(762, "black-glasses.png");
            this.itemImages.Images.SetKeyName(763, "black-sludge.png");
            this.itemImages.Images.SetKeyName(764, "blastoisinite.png");
            this.itemImages.Images.SetKeyName(765, "blazikenite.png");
            this.itemImages.Images.SetKeyName(766, "bloom-mail.png");
            this.itemImages.Images.SetKeyName(767, "blue-apricorn.png");
            this.itemImages.Images.SetKeyName(768, "blue-card.png");
            this.itemImages.Images.SetKeyName(769, "blue-flute.png");
            this.itemImages.Images.SetKeyName(770, "blue-orb.png");
            this.itemImages.Images.SetKeyName(771, "blue-petal.png");
            this.itemImages.Images.SetKeyName(772, "blue-scarf.png");
            this.itemImages.Images.SetKeyName(773, "blue-shard.png");
            this.itemImages.Images.SetKeyName(774, "bluk-berry.png");
            this.itemImages.Images.SetKeyName(775, "boost-mulch.png");
            this.itemImages.Images.SetKeyName(776, "bottle-cap.png");
            this.itemImages.Images.SetKeyName(777, "brick-mail.png");
            this.itemImages.Images.SetKeyName(778, "bridge-mail-d.png");
            this.itemImages.Images.SetKeyName(779, "bridge-mail-m.png");
            this.itemImages.Images.SetKeyName(780, "bridge-mail-s.png");
            this.itemImages.Images.SetKeyName(781, "bridge-mail-t.png");
            this.itemImages.Images.SetKeyName(782, "bridge-mail-v.png");
            this.itemImages.Images.SetKeyName(783, "bright-powder.png");
            this.itemImages.Images.SetKeyName(784, "bubble-mail.png");
            this.itemImages.Images.SetKeyName(785, "bug-gem.png");
            this.itemImages.Images.SetKeyName(786, "buginium-z--bag.png");
            this.itemImages.Images.SetKeyName(787, "buginium-z--held.png");
            this.itemImages.Images.SetKeyName(788, "bug-memory.png");
            this.itemImages.Images.SetKeyName(789, "burn-drive.png");
            this.itemImages.Images.SetKeyName(790, "burn-heal.png");
            this.itemImages.Images.SetKeyName(791, "calcium.png");
            this.itemImages.Images.SetKeyName(792, "cameruptite.png");
            this.itemImages.Images.SetKeyName(793, "carbos.png");
            this.itemImages.Images.SetKeyName(794, "card-key.png");
            this.itemImages.Images.SetKeyName(795, "casteliacone.png");
            this.itemImages.Images.SetKeyName(796, "cell-battery.png");
            this.itemImages.Images.SetKeyName(797, "charcoal.png");
            this.itemImages.Images.SetKeyName(798, "charizardite-x.png");
            this.itemImages.Images.SetKeyName(799, "charizardite-y.png");
            this.itemImages.Images.SetKeyName(800, "charti-berry.png");
            this.itemImages.Images.SetKeyName(801, "cheri-berry.png");
            this.itemImages.Images.SetKeyName(802, "cherish-ball.png");
            this.itemImages.Images.SetKeyName(803, "chesto-berry.png");
            this.itemImages.Images.SetKeyName(804, "chilan-berry.png");
            this.itemImages.Images.SetKeyName(805, "chill-drive.png");
            this.itemImages.Images.SetKeyName(806, "choice-band.png");
            this.itemImages.Images.SetKeyName(807, "choice-scarf.png");
            this.itemImages.Images.SetKeyName(808, "choice-specs.png");
            this.itemImages.Images.SetKeyName(809, "chople-berry.png");
            this.itemImages.Images.SetKeyName(810, "claw-fossil.png");
            this.itemImages.Images.SetKeyName(811, "cleanse-tag.png");
            this.itemImages.Images.SetKeyName(812, "clear-bell.png");
            this.itemImages.Images.SetKeyName(813, "clever-wing.png");
            this.itemImages.Images.SetKeyName(814, "coba-berry.png");
            this.itemImages.Images.SetKeyName(815, "coin-case.png");
            this.itemImages.Images.SetKeyName(816, "colbur-berry.png");
            this.itemImages.Images.SetKeyName(817, "colress-machine.png");
            this.itemImages.Images.SetKeyName(818, "comet-shard.png");
            this.itemImages.Images.SetKeyName(819, "common-stone.png");
            this.itemImages.Images.SetKeyName(820, "contest-costume--dress.png");
            this.itemImages.Images.SetKeyName(821, "contest-costume--jacket.png");
            this.itemImages.Images.SetKeyName(822, "contest-pass.png");
            this.itemImages.Images.SetKeyName(823, "cornn-berry.png");
            this.itemImages.Images.SetKeyName(824, "coupon-1.png");
            this.itemImages.Images.SetKeyName(825, "coupon-2.png");
            this.itemImages.Images.SetKeyName(826, "coupon-3.png");
            this.itemImages.Images.SetKeyName(827, "cover-fossil.png");
            this.itemImages.Images.SetKeyName(828, "ability-capsule.png");
            this.itemImages.Images.SetKeyName(829, "ability-urge.png");
            this.itemImages.Images.SetKeyName(830, "abomasite.png");
            this.itemImages.Images.SetKeyName(831, "absolite.png");
            this.itemImages.Images.SetKeyName(832, "absorb-bulb.png");
            this.itemImages.Images.SetKeyName(833, "acro-bike.png");
            this.itemImages.Images.SetKeyName(834, "adamant-orb.png");
            this.itemImages.Images.SetKeyName(835, "adrenaline-orb.png");
            this.itemImages.Images.SetKeyName(836, "adventure-rules.png");
            this.itemImages.Images.SetKeyName(837, "aerodactylite.png");
            this.itemImages.Images.SetKeyName(838, "aggronite.png");
            this.itemImages.Images.SetKeyName(839, "aguav-berry.png");
            this.itemImages.Images.SetKeyName(840, "air-balloon.png");
            this.itemImages.Images.SetKeyName(841, "air-mail.png");
            this.itemImages.Images.SetKeyName(842, "alakazite.png");
            this.itemImages.Images.SetKeyName(843, "aloraichium-z--bag.png");
            this.itemImages.Images.SetKeyName(844, "aloraichium-z--held.png");
            this.itemImages.Images.SetKeyName(845, "altarianite.png");
            this.itemImages.Images.SetKeyName(846, "amaze-mulch.png");
            this.itemImages.Images.SetKeyName(847, "ampharosite.png");
            this.itemImages.Images.SetKeyName(848, "amulet-coin.png");
            this.itemImages.Images.SetKeyName(849, "antidote.png");
            this.itemImages.Images.SetKeyName(850, "apicot-berry.png");
            this.itemImages.Images.SetKeyName(851, "apricorn-box.png");
            this.itemImages.Images.SetKeyName(852, "aqua-suit.png");
            this.itemImages.Images.SetKeyName(853, "armor-fossil.png");
            this.itemImages.Images.SetKeyName(854, "aspear-berry.png");
            this.itemImages.Images.SetKeyName(855, "assault-vest.png");
            this.itemImages.Images.SetKeyName(856, "audinite.png");
            this.itemImages.Images.SetKeyName(857, "auroraticket.png");
            this.itemImages.Images.SetKeyName(858, "awakening.png");
            this.itemImages.Images.SetKeyName(859, "azure-flute.png");
            this.itemImages.Images.SetKeyName(860, "babiri-berry.png");
            this.itemImages.Images.SetKeyName(861, "balm-mushroom.png");
            this.itemImages.Images.SetKeyName(862, "banettite.png");
            this.itemImages.Images.SetKeyName(863, "basement-key.png");
            this.itemImages.Images.SetKeyName(864, "basement-key--goldenrod.png");
            this.itemImages.Images.SetKeyName(865, "basement-key--new-mauville.png");
            this.itemImages.Images.SetKeyName(866, "bead-mail.png");
            this.itemImages.Images.SetKeyName(867, "beast-ball.png");
            this.itemImages.Images.SetKeyName(868, "beedrillite.png");
            this.itemImages.Images.SetKeyName(869, "belue-berry.png");
            this.itemImages.Images.SetKeyName(870, "berry-juice.png");
            this.itemImages.Images.SetKeyName(871, "berry-pots.png");
            this.itemImages.Images.SetKeyName(872, "berry-pouch.png");
            this.itemImages.Images.SetKeyName(873, "bicycle.png");
            this.itemImages.Images.SetKeyName(874, "bicycle-turquoise.png");
            this.itemImages.Images.SetKeyName(875, "bicycle-yellow.png");
            this.itemImages.Images.SetKeyName(876, "big-malasada.png");
            this.itemImages.Images.SetKeyName(877, "big-mushroom.png");
            this.itemImages.Images.SetKeyName(878, "big-nugget.png");
            this.itemImages.Images.SetKeyName(879, "big-pearl.png");
            this.itemImages.Images.SetKeyName(880, "big-root.png");
            this.itemImages.Images.SetKeyName(881, "bike--green.png");
            this.itemImages.Images.SetKeyName(882, "bike-voucher.png");
            this.itemImages.Images.SetKeyName(883, "bike--yellow.png");
            this.itemImages.Images.SetKeyName(884, "binding-band.png");
            this.itemImages.Images.SetKeyName(885, "black-apricorn.png");
            this.itemImages.Images.SetKeyName(886, "black-belt.png");
            // 
            // PokemonUIForm
            // 
            resources.ApplyResources(this, "$this");
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.desktopPanel);
            this.Controls.Add(this.menuTitlePanel);
            this.Controls.Add(this.menuPanel);
            this.Name = "PokemonUIForm";
            this.Load += new System.EventHandler(this.PokemonUIForm_Load);
            this.menuPanel.ResumeLayout(false);
            this.menuPanel.PerformLayout();
            this.buttonsPanel.ResumeLayout(false);
            this.logoPanel.ResumeLayout(false);
            this.menuTitlePanel.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel menuPanel;
        private System.Windows.Forms.Button settingsButton;
        private System.Windows.Forms.Button pokemonButton;
        private System.Windows.Forms.Button itemsButton;
        private System.Windows.Forms.Button movesButton;
        private System.Windows.Forms.Button teamsButton;
        private System.Windows.Forms.Panel logoPanel;
        private System.Windows.Forms.ImageList icons;
        private System.Windows.Forms.Label appTitleLabel;
        private System.Windows.Forms.Panel menuTitlePanel;
        private System.Windows.Forms.Label menuTitleLabel;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Panel buttonsPanel;
        private System.Windows.Forms.Panel desktopPanel;
        private System.Windows.Forms.ImageList types;
        private System.Windows.Forms.ComboBox comboBox1;
        internal System.Windows.Forms.ImageList itemImages;
        internal System.Windows.Forms.ImageList pokemonImages;
    }
}

