//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamDexLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamDexLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:1,&quot;Name&quot;:&quot;stench&quot;},{&quot;Id&quot;:2,&quot;Name&quot;:&quot;drizzle&quot;},{&quot;Id&quot;:3,&quot;Name&quot;:&quot;speed-boost&quot;},{&quot;Id&quot;:4,&quot;Name&quot;:&quot;battle-armor&quot;},{&quot;Id&quot;:5,&quot;Name&quot;:&quot;sturdy&quot;},{&quot;Id&quot;:6,&quot;Name&quot;:&quot;damp&quot;},{&quot;Id&quot;:7,&quot;Name&quot;:&quot;limber&quot;},{&quot;Id&quot;:8,&quot;Name&quot;:&quot;sand-veil&quot;},{&quot;Id&quot;:9,&quot;Name&quot;:&quot;static&quot;},{&quot;Id&quot;:10,&quot;Name&quot;:&quot;volt-absorb&quot;},{&quot;Id&quot;:11,&quot;Name&quot;:&quot;water-absorb&quot;},{&quot;Id&quot;:12,&quot;Name&quot;:&quot;oblivious&quot;},{&quot;Id&quot;:13,&quot;Name&quot;:&quot;cloud-nine&quot;},{&quot;Id&quot;:14,&quot;Name&quot;:&quot;compound-eyes&quot;},{&quot;Id&quot;:15,&quot;Name&quot;:&quot;insomnia&quot;},{&quot;Id&quot;:16,&quot;Name&quot;:&quot;color-change&quot;},{&quot;Id&quot;:17,&quot;Name&quot;:&quot;immunity&quot;},{&quot;Id&quot;:18,&quot;Name....
        /// </summary>
        internal static string ability {
            get {
                return ResourceManager.GetString("ability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:1,&quot;Name&quot;:&quot;master-ball&quot;},{&quot;Id&quot;:2,&quot;Name&quot;:&quot;ultra-ball&quot;},{&quot;Id&quot;:3,&quot;Name&quot;:&quot;great-ball&quot;},{&quot;Id&quot;:4,&quot;Name&quot;:&quot;poke-ball&quot;},{&quot;Id&quot;:5,&quot;Name&quot;:&quot;safari-ball&quot;},{&quot;Id&quot;:6,&quot;Name&quot;:&quot;net-ball&quot;},{&quot;Id&quot;:7,&quot;Name&quot;:&quot;dive-ball&quot;},{&quot;Id&quot;:8,&quot;Name&quot;:&quot;nest-ball&quot;},{&quot;Id&quot;:9,&quot;Name&quot;:&quot;repeat-ball&quot;},{&quot;Id&quot;:10,&quot;Name&quot;:&quot;timer-ball&quot;},{&quot;Id&quot;:11,&quot;Name&quot;:&quot;luxury-ball&quot;},{&quot;Id&quot;:12,&quot;Name&quot;:&quot;premier-ball&quot;},{&quot;Id&quot;:13,&quot;Name&quot;:&quot;dusk-ball&quot;},{&quot;Id&quot;:14,&quot;Name&quot;:&quot;heal-ball&quot;},{&quot;Id&quot;:15,&quot;Name&quot;:&quot;quick-ball&quot;},{&quot;Id&quot;:16,&quot;Name&quot;:&quot;cherish-ball&quot;},{&quot;Id&quot;:17,&quot;Name&quot;:&quot;potion&quot;},{&quot;Id&qu....
        /// </summary>
        internal static string item {
            get {
                return ResourceManager.GetString("item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:1,&quot;Name&quot;:&quot;pound&quot;,&quot;Type&quot;:1,&quot;Power&quot;:&quot;40&quot;,&quot;Pp&quot;:&quot;35&quot;},{&quot;Id&quot;:2,&quot;Name&quot;:&quot;karate-chop&quot;,&quot;Type&quot;:2,&quot;Power&quot;:&quot;50&quot;,&quot;Pp&quot;:&quot;25&quot;},{&quot;Id&quot;:3,&quot;Name&quot;:&quot;double-slap&quot;,&quot;Type&quot;:1,&quot;Power&quot;:&quot;15&quot;,&quot;Pp&quot;:&quot;10&quot;},{&quot;Id&quot;:4,&quot;Name&quot;:&quot;comet-punch&quot;,&quot;Type&quot;:1,&quot;Power&quot;:&quot;18&quot;,&quot;Pp&quot;:&quot;15&quot;},{&quot;Id&quot;:5,&quot;Name&quot;:&quot;mega-punch&quot;,&quot;Type&quot;:1,&quot;Power&quot;:&quot;80&quot;,&quot;Pp&quot;:&quot;20&quot;},{&quot;Id&quot;:6,&quot;Name&quot;:&quot;pay-day&quot;,&quot;Type&quot;:1,&quot;Power&quot;:&quot;40&quot;,&quot;Pp&quot;:&quot;20&quot;},{&quot;Id&quot;:7,&quot;Name&quot;:&quot;fire-punch&quot;,&quot;Type&quot;:10,&quot;Power&quot;:&quot;75&quot;,&quot;Pp&quot;:&quot;15&quot;},{&quot;Id&quot;:8,&quot;Name&quot;:&q....
        /// </summary>
        internal static string move {
            get {
                return ResourceManager.GetString("move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:1,&quot;Name&quot;:&quot;bulbasaur&quot;,&quot;Types&quot;:[12,4]},{&quot;Id&quot;:2,&quot;Name&quot;:&quot;ivysaur&quot;,&quot;Types&quot;:[12,4]},{&quot;Id&quot;:3,&quot;Name&quot;:&quot;venusaur&quot;,&quot;Types&quot;:[12,4]},{&quot;Id&quot;:4,&quot;Name&quot;:&quot;charmander&quot;,&quot;Types&quot;:[10]},{&quot;Id&quot;:5,&quot;Name&quot;:&quot;charmeleon&quot;,&quot;Types&quot;:[10]},{&quot;Id&quot;:6,&quot;Name&quot;:&quot;charizard&quot;,&quot;Types&quot;:[10,3]},{&quot;Id&quot;:7,&quot;Name&quot;:&quot;squirtle&quot;,&quot;Types&quot;:[11]},{&quot;Id&quot;:8,&quot;Name&quot;:&quot;wartortle&quot;,&quot;Types&quot;:[11]},{&quot;Id&quot;:9,&quot;Name&quot;:&quot;blastoise&quot;,&quot;Types&quot;:[11]},{&quot;Id&quot;:10,&quot;Name&quot;:&quot;caterpie&quot;,&quot;Types&quot;:[7]},{&quot;Id&quot;:11,&quot;Name&quot;:&quot;metapod&quot;,&quot;Types&quot;:[7]},{&quot;Id&quot;:12,&quot;Name&quot;:&quot;butterfree&quot;,&quot;Types&quot;:[7,3]},{&quot;Id&quot;:13,&quot;Nam [rest of stri....
        /// </summary>
        internal static string pokedex {
            get {
                return ResourceManager.GetString("pokedex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:1,&quot;Name&quot;:&quot;normal&quot;,&quot;DoubleDamage&quot;:[2,2,2,2,2,3,3,3,4,4,5,5,5,5,5,6,6,6,6,7,7,7,8,8,9,9,9,10,10,10,10,11,11,11,12,12,12,13,13,14,14,15,15,15,15,16,17,17,18,18,18],&quot;HalfDamage&quot;:[1,1,2,2,2,2,2,3,3,3,4,4,4,4,5,5,6,6,6,7,7,7,7,7,7,7,8,9,9,9,9,10,10,10,10,11,11,11,12,12,12,12,12,12,12,13,13,13,14,14,15,15,15,15,16,17,17,17,18,18,18],&quot;NoEffect&quot;:[1,2,4,5,8,13,14,16]},{&quot;Id&quot;:2,&quot;Name&quot;:&quot;fighting&quot;,&quot;DoubleDamage&quot;:[2,2,2,2,2,3,3,3,4,4,5,5,5,5,5,6,6,6,6,7,7,7,8,8,9,9,9,10,10,10,10,11,11,11,12,12,12,13,13,14,14,15,15, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
    }
}
